### ISSUE TITLE
docs broken?

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#102]
I can't open any modal on your docs page 😅 
https://vue-final-modal.org/examples/manual/#hello-vue-final-modal
<img width="452" alt="image" src="https://user-images.githubusercontent.com/3253920/118363704-a0c4a900-b5d0-11eb-89b1-5307080f52ef.png">

**Comment by hunterliu1003** [comment]
@mesqueeb
The document has been fixed.
