### ISSUE TITLE
Programmatic renderning

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#103]
### Is your feature request related to a problem? Please describe.

Often I need to create small confirmation modals. I have a nifty setup with Quasar where I invented some programmatic dialog creation like so:

```js
Dialog.create({
  slotComponent: 'Confirmation',
  slotProps: {
    title: 'really delete?'
    buttons: ['ok', 'cancel']
  },
  slotEvents: {
    ok: () => {
      console.log('deletion confirmed')
    }
  }
})
```

Quasar semi supports this, but I had to extend the original logic some more to make it work.

**I'm trying to get off of Quasar though...** I want to go vanilla Vue!!

### Describe the solution you'd like

I'm looking for a programmatic syntax I could use similar to the above that renders a dialog out of noting _just_ via programmatic execution.

The idea is that you are able to pass any component which the function renders inside the dialog with `component is=""`.

This way you can easily render any component inside a component via programatic execution.

### Describe alternatives you've considered

Find another library or help writing this logic in a PR for this one.

### Additional context

I'm really looking for a lightweight dialog solution. But programmatic rendering is important. I hope we can work on this feature maybe together.

**Comment by hunterliu1003** [comment]
Hi @mesqueeb,

Thank you for the proposal. The feature  seems to be similar to the `Dynamic modal`.

## Advanced dynamic modal

Checkout live demo here [`Advanced dynamic modal`](https://vue-final-modal.org/dynamic-modal#advanced).

```js
import VContent from '../VContent.vue'

this.$vfm.show({
  component: 'VModal',
  bind: {
    // bind props for VModal and VueFinalModal
    name: 'VDynamicAdvacedModal'
  },
  on: {
    // event by v-modal
    confirm(close) {
      console.log('confirm')
      close()
    },
    // event by vue-final-modal
    'click-outside'() {
      console.log('@click-outside')
    },
    'before-open'() {
      console.log('@before-open')
    }
  },
  slots: {
    title: {
      component: 'VTitle',
      bind: {
        text: 'Hello, vue-final-modal'
      }
    },
    default: {
      component: VContent,
      bind: {
        content:
          'Vue Final Modal is a renderless, stackable, detachable and lightweight modal component.'
      }
    }
  }
})
```

Hope this solves your problem

**Comment by mesqueeb** [comment]
Dynamic model seems to be the exact thing I needed!
Sorry I must've missed this!

I'll let you know if I have any further feature requests, but I think I'll use your library.
