### ISSUE TITLE
FR: fullscreen prop

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#105]
### Is your feature request related to a problem? Please describe.

I'd love a simple prop `fullscreen: Boolean` to be able to switch the modal style to be full screen or not.

### Describe the solution you'd like

a simple prop `fullscreen: Boolean`

### Describe alternatives you've considered

Manually overriding the CSS?

**Comment by hunterliu1003** [comment]
Hi @mesqueeb,
Considering that vfm is a [renderless](https://adamwathan.me/renderless-components-in-vuejs/) component, I try not to pre-define any CSS as much as possible.

Here is a example:

https://codepen.io/hunterliu1003/pen/MWpeZZp

**Comment by mesqueeb** [comment]
@hunterliu1003 thanks a lot ! I agree with not predefining CSS related stuff.

maybe you could add this example to the docs! : )
