### ISSUE TITLE
Cannot read property 'removeEventListener' of undefined when using resize in nuxt and navigating away

### ISSUE THREAD

**Issue by jeffalo** [vue-final/vue-final-modal#106]
![image](https://user-images.githubusercontent.com/40470736/119330588-a718ec00-bc86-11eb-916c-688ff377eb8a.png)

### Version

vue-final-modal@2.3.0
nuxt@2.15.4

### OS

Windows 10, Chrome 90.0.4430.212 

### Reproduction Link
I am experiencing this error in development, and it also affects the live demo at https://vue-final-modal.org/examples/liveDemo

### Steps to reproduce

1. Make sure `resize` is true
2. Open & close modal
2. Open console
3. Navigate to another page using the links in the sidebar
4. You see this error
![image](https://user-images.githubusercontent.com/40470736/119330269-50abad80-bc86-11eb-8344-3319dc4cb246.png)

I think this has something to do with how Nuxt page navigations work, perhaps the modal element no longer exists after navigation? Strangely this only happens when resize is true.

### What is Expected?
There are no errors.

### What is actually happening?
You see an error (above)

**Comment by jeffalo** [comment]
Also, thank you so much for this component. It is very useful for my website.

**Comment by hunterliu1003** [comment]
Hi @jeffalo,

Thank you for reporting this issue. I will fix it in the next few days.

**Comment by hunterliu1003** [comment]
Fixed and Released in [vue-final-modal@2.3.1](https://github.com/vue-final/vue-final-modal/releases/tag/v2.3.1)

**Comment by jeffalo** [comment]
Thank you so much. That was very fast!!
