### ISSUE TITLE
Inconsistent property name cases in documentation

### ISSUE THREAD

**Issue by mankey-ru** [vue-final/vue-final-modal#110]
https://vue-final-modal.org/guide/properties

In [Overview](https://vue-final-modal.org/guide/properties#overview-the-default-value-of-properties) prop names are in mixed case: mostly kebab-case and a bit of camelCase:
```
:focus-trap="false"
:fitParent="true"
```

In [detailed info](https://vue-final-modal.org/guide/properties#focustrap) prop names are in camelCase: `focusTrap`

Please choose one particular case and make names consistent. Thank you!

**Comment by hunterliu1003** [comment]
Hi @mankey-ru,

Thank you for your suggestion, I have changed all props to use kebeb-case.
