### ISSUE TITLE
Modal is closing when I select text with mousedown inside and mouseup outside modal

### ISSUE THREAD

**Issue by mankey-ru** [vue-final/vue-final-modal#111]
### Version

vue-final-modal: 2.3.1
vue: 2.6.12

### OS

Windows

### Reproduction Link
https://codesandbox.io/s/cocky-night-0ysyb?file=/src/App.vue

### Steps to reproduce
Select the text with a sloppy move: mousedown is inside the modal and mouse button released when cursor is on overlay

### What is Expected?
Text is selected and modal is not closed

### What is actually happening?
modal closed. Probably event type should be `mousedown` **OR** event handler should check [Window.getSelection()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection)

**Comment by hunterliu1003** [comment]
Hi @mankey-ru,

Thank you for providing good reproduction. I will study if there is any good solution.

**Comment by hunterliu1003** [comment]
The bugfix will be released in 

v2.3.2 for Vue 2
v3.3.1 for Vue3

**Comment by hunterliu1003** [comment]
The bugfix was released in

v2.3.2 for Vue 2
v3.3.1 for Vue3
