### ISSUE TITLE
docs: fix broken page

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#115]
this page seems to be broken currently:

https://v3.vue-final-modal.org/examples/livedemo/

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3253920/120959594-14ec0a00-c795-11eb-8631-a2bfb71d00c4.png">

**Comment by hunterliu1003** [comment]
Thanks, I just fixed it and deploy the new version
