### ISSUE TITLE
Is there a property for dark mode?

### ISSUE THREAD

**Issue by mspoulsen** [vue-final/vue-final-modal#116]
Hi,

I am trying to integrate vue-final-modal with a vuetify app which has light/dark themes.
Is there a way to control light/dark mode on the modal via a prop?

Thanks :+1:

**Comment by hunterliu1003** [comment]
Hey @mspoulsen,

Due to vue-final-modal was an renderless component, so without built-in light/dark mode.
I wrote HOC modal that support light/dark mode, please check it out: 

https://codesandbox.io/s/7ylsn

**Comment by mspoulsen** [comment]
@hunterliu1003 
Excellent! Thanks a lot. I am trying to fit the modal into a rather large Vuetify app. The dialogs in Vuetify are not movable and I need that feature. Do you have any tips on how to make the two play well together. I am looking to avoid any CSS styling if possible.

**Comment by hunterliu1003** [comment]
I found this
https://github.com/vuetifyjs/vuetify/issues/4058#issuecomment-450636420
you can try it out.
Or you can write a HOC modal component called VDialog to replace all vuetify dialog

**Comment by mspoulsen** [comment]
Thanks :+1:
