### ISSUE TITLE
App is nudged behind the modal when modal is opened

### ISSUE THREAD

**Issue by mspoulsen** [vue-final/vue-final-modal#127]
When I open the modal, my app is nudged about 10 pixels to the left. See this video:

https://www.loom.com/share/13c8128f61404bf8b53a612f2d0dd39c

Any idea why? 
Thanks :)

**Comment by hunterliu1003** [comment]
vue-final-modal using body-scroll-lock for lock body when modal opened. body-scroll-lock add style `overflow: hidden; padding-right: scrollbar width` to the body.

You can try set prop `lock-scroll=“false”` then check if the issue is resolved

**Comment by hunterliu1003** [comment]
You can re-open this issue if your problem is not resolved
