### ISSUE TITLE
Is it possible to give the background focus?

### ISSUE THREAD

**Issue by mspoulsen** [vue-final/vue-final-modal#128]
Not sure if I am wording this right, but what I am trying to say is that I would like to be able to click icons in the background when the modal is open:

https://www.loom.com/share/017627ef9a164927ba757e86165fe778

The modal is stealing all of the focus (which is perfectly normal). But is there a way to change that?

Thank you very much :)

**Comment by hunterliu1003** [comment]
You can re-open this issue if your problem is not resolved
