### ISSUE TITLE
attach="body" need fixed position

### ISSUE THREAD

**Issue by sinau123** [vue-final/vue-final-modal#130]
### Is your feature request related to a problem? Please describe.
I want to attach the modal to the `body` element, so I add `attach="body"`. The problem is modal overlay is not fit to page, there is a gap on the left, because it use absolute position

### Describe the solution you'd like
so the solution, when we add attach="body", use class 'vfm--fixed' instead. Because attach to body is different with attach to other element, it is like 'put this modal to the whole page'.

https://github.com/vue-final/vue-final-modal/blob/65edad5d39410a8b8e6fa5a9cc53142cc4de09f0/lib/VueFinalModal.vue#L7

### Additional context

sandbox:
https://codesandbox.io/s/mystifying-sutherland-n1l0q?file=/src/App.vue

sorry for my bad English and thanks for your hardwork in this project..

**Comment by hunterliu1003** [comment]
@sinau123 
I thought you can reset the default style in body with `reset.css` or `normalize.css`.
The gap is actually the default margin in body element.

**Comment by hunterliu1003** [comment]
Checkout the example: https://codesandbox.io/s/fancy-violet-rxcc8
```css
body {
  position: relative;
  margin: 0;
}
```

**Comment by hunterliu1003** [comment]
You can re-open this issue if your problem is not resolved
