### ISSUE TITLE
DISPLAY:NONE in MODAL AFTER CLOSE!

### ISSUE THREAD

**Issue by phantoxe** [vue-final/vue-final-modal#132]
### Version

vue-final-modal: 3.3.0
vue: 3.0.5
nuxt: im not using nuxt

### OS

Windows

### Reproduction Link

https://github.com/phantoxe/vite-app

### Steps to reproduce

Just RUN SERVER and in HEADER click in button "ENTRAR".

### What is Expected?

The VUE gonna open MODAL ok? Then you click out and gonna close the MODAL. It is correct!

### What is actually happening?

But now... you CAN TRY click again in the button 'ENTRAR'. You see? I cant click again!

**Comment by hunterliu1003** [comment]
@phantoxe 
You have to give independent data binding with v-model to each vue-final-modal component.

```vue
<template>
  <vue-final-modal v-model="showCadastro" name="cadastro" :esc-to-close="true" classes="flex justify-center items-center">
    <div class="modal-cadastro">
      Ae PORRA!
    </div>
  </vue-final-modal>
  <vue-final-modal v-model="showLogin" name="login" :esc-to-close="true" classes="flex justify-center items-center">
    <div class="modal-cadastro">
      Esse é do LOGIN
    </div>
  </vue-final-modal>
</template>

<script>
export default {
  data: () => ({
      showCadastro: false,
      showLogin: false
  }),
  methods: {
    openModalExample(tipo) {
      this.$vfm.show(tipo)
    }
  }
}
</script>
```
