### ISSUE TITLE
Allow import $vfm, VueFinalModal, ModalsContainer directly 

### ISSUE THREAD

**Issue by hunterliu1003** [vue-final/vue-final-modal#134]
For example:

```js
import { vfmPlugin, $vfm, VueFInalModal, ModalsContainer } from 'vue-final-modal'
```

**Comment by Froxz** [comment]
Hi @hunterliu1003 whe this will be released?

**Comment by hunterliu1003** [comment]
Hi @Froxz,

This is released in v2.4 version for support Vue 2

But I still working on the Vue 3 version of this

**Comment by hunterliu1003** [comment]
Released in v3.4 version for support Vue 3

**Comment by Froxz** [comment]
Hi @hunterliu1003 

I don't think this is working:

In my App.vue I have only:

```js
import { $vfm, ModalsContainer } from 'vue-final-modal'

...
openVideo(src){

    $vfm.show({
		 component: defineAsyncComponent(() => import('@components/Youtube')),
		 bind: {
	              	src
	          }
	})
}
```
In my YouTube.vue:
```js
import Modal from '@components/Modal'
```

In my Modal.vue:
```js
import { VueFinalModal } from 'vue-final-modal'
```


So as you can see, the YouTube component is lazyloaded when `$vfm.show` is called.

But on page load I can see styles added by `vue-final-modal`, which shouldn't happen becuase is not loaded yet, I think Tree-Shaking is not working correctly, or is just me.

**Comment by hunterliu1003** [comment]
As long as you import one of `$vfm`, `VueFinalModal`, `ModalContainer` from `vue-final-modal`, it will load every module from vue-final-modal. You can't split and do tree-shaking only at `VueFinalModal.vue` component, because the `VueFinalModal`, `ModalsContainer` components have to connect with the `$vfm`.

But lazyload YouTube component is working for me. If you need a example, please let me know.

**Comment by hunterliu1003** [comment]
Just a remind that this can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw`.

```js
import { defineAsyncComponent, markRaw } from 'vue'

export default {
  methods: {
    dynamic() {
      this.$vfm.show({
        component: markRaw(defineAsyncComponent(() => import('../hoc/CustomModal.vue'))),
      })
    }
  }
}
```

**Comment by Froxz** [comment]
Hi @hunterliu1003 thank you for the hint ‘markRaw’

what if we connect all 3 with a small state manager? This way we can load things what needed at that time?

**Comment by hunterliu1003** [comment]
I'm not sure what you mean that connect all 3 with a small state manager.
`lib/VueFinalModa.vue` should be created by `defineModal`:

https://github.com/vue-final/vue-final-modal/blob/b5038c580e392c9a8fb3b8ddf5fe1152107d8423/lib/PluginCore.js#L1
https://github.com/vue-final/vue-final-modal/blob/b5038c580e392c9a8fb3b8ddf5fe1152107d8423/lib/PluginCore.js#L65-L69

and export from:

https://github.com/vue-final/vue-final-modal/blob/b5038c580e392c9a8fb3b8ddf5fe1152107d8423/lib/Plugin.js#L28

So that it is different between

```js
// not work
import VueFinalModal from 'vue-final-modal/lib/VueFinalModal.vue
```

and

```js
// work
import { VueFinalModal } from 'vue-final-modal'
```
