### ISSUE TITLE
[use-modal-hook] How to update the props of a dynamic modal after the modal was opened?

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#139]
How to update the props of a dynamic modal after the modal was opened?

**Comment by enemy-senator92** [comment]
Hey! it would be interesting for me too

**Comment by mesqueeb** [comment]
Wtf is wrong with you, look at your profile picture. Please change it dude, it's very disturbing

**Comment by theartkod** [comment]
> Wtf is wrong with you, look at your profile picture. Please change it dude, it's very disturbing

Seriously? Watch for you tone, please.

It's quite toxicity.

**Comment by mesqueeb** [comment]
I believe a photo of a baby that has bruises should be illigal.

**Comment by theartkod** [comment]
btw, it's avatar from movie called "Chucky" and nothing illegal there

**Comment by hunterliu1003** [comment]
Hey guys,

I have an idea that allow developer define a dynamic modal by using `useModal` hook:

```js
const [show, hide, options] = useModal({
   ...dynamicModalOptions
})

show() // show dynamic modal

hide() // hide dynamic modal

options.bind.hideOverlay = true // update the binding props of a dynamic modal
```

`options` is a two-way bindings object based on `dynamicModalOptions`, that means:
- In Vue 2: using `Vue.observable` for two-way data bindings
- In Vue 3: using `reactive` for two-way data bindings

What do you think?

**Comment by mesqueeb** [comment]
I would go for this syntax:
```js
const { showModal, hideModal, toggleModal, modalOptions } = useModal({
   ...dynamicModalOptions
})
```

**Comment by hunterliu1003** [comment]
yeah, using object destructuring assignment is better

**Comment by hunterliu1003** [comment]
The `useModal` will be released very soon in vue-final-modal@4
