### ISSUE TITLE
About focus after closing in IE11

### ISSUE THREAD

**Issue by k-s-h-r** [vue-final/vue-final-modal#140]
### Version
vue-final-modal: 2.4.1
vue: 2.6.14

### OS
Windows

### Browser
IE11

### Steps to reproduce
1. Create a modal
2. Create a button to open the modal
3. Click the button to open the modal
4. Click off screen to close the modal (you can also use the close button inside the modal)
5. Press the `tab` key
6. The focus element at the top of the page is in focus

### What is Expected?
In IE11, like other browsers, if you press the focus key after closing the modal, you want to focus on the element that opened the modal.

Is ie11 unsupported?

**Comment by hunterliu1003** [comment]
what is `Press the focus key` mean?

**Comment by k-s-h-r** [comment]
sorry, it's the `tab` key

**Comment by hunterliu1003** [comment]
please checkout [focustrap prop](https://v2.vue-final-modal.org/guide/properties#focus-trap)
