### ISSUE TITLE
Is there any way to open modal using vanilla Javascript ?

### ISSUE THREAD

**Issue by SirMishaa** [vue-final/vue-final-modal#143]
I have a special question, I have a navbar with buttons, like login / register. 

I'm using Vue as a component library, not an SPA. I use it with Blade (Laravel's template engine).

That's why I would like to be able to open a login modal with simple JavaScript because otherwise I'll have to have the buttons of my navbar in a Vue component, which annoys me a bit.

Do you know how I can do that? 

Thank you in advance

**Comment by hunterliu1003** [comment]
If you have a login modal with a name `login`
You can use this.$vfm.show('login') to open the modal.
Please checkout the docs here: https://vue-final-modal.org/api#vfmshowname-params

**Comment by hunterliu1003** [comment]
Feel free to reopen this if my response don't solve your question
