### ISSUE TITLE
syntax suggestions

### ISSUE THREAD

**Issue by mesqueeb** [vue-final/vue-final-modal#144]
Props
=====

name
→ modal-id
	(name is too vague)

ssr
→ prerender
→ hide-method ('v-show', 'v-if')
→ render-method ('v-show', 'v-if')
→ show-method ('v-show', 'v-if')
→ render-with ('v-show', 'v-if')
	(ssr is too vague, because it's not clear what exactly this prop _does_)
	(in my capacitor app, I have many situations I have to make a conscious decision about if I want to hide the modal with v-if or v-show. In order to decide stuff related to performance AND the mounted hook.)

hide-overlay
→ show-overlay: `true`
  (no negative prop names)

prevent-click
→ overlay-pointer-events: 'none', 'auto'

attach
→ teleport-to
  (remove prop and make a use-case doc instead)

z-index-auto
  (you don't need this prop, remove it, if the dev doesn't pass any `z-index` or `z-index-base` then it will be `auto` either way.)

focus-retain
→ focus-modal: false
→ focus-on-show: false
	(I think you don't need this prop at all)

drag & resize related stuff
→ maybe convert to a vue-directive that you export as well, a user can import and use the vue-directive
→ OR see if you can find another library like `vueuse/gesture` and just write a clear example use-case

fit-parent
→ use-parent-boundries

keep-changed-style
→ personally, i think it can be true by default

IF you decide to keep `drag` and `resize` I would change the props to be:
- drag-options: { enabled: true, minWidth: 100, handler: '.something' }
- resize-options: { enabled: false, ... } // default

---

events
======
@closed
  (you have to clarify if/when this is emitted based on `ssr: true/false`)
  I'd write something like:
  "This is emitted no matter if you use `ssr: true` or `ssr: false`"

params
======
I would call this "slot scope", not "params".
If you think it's a bad practice, you should get rid of it, and make a section in the docs about what to do in the situation someone feels they need it.

**Comment by hunterliu1003** [comment]
> If you think it's a bad practice, you should get rid of it, and make a section in the docs about what to do in the situation someone feels they need it.

Thanks @mesqueeb. This is the best suggestion I got today.

English is so hard than Javascript haha.

Big thank to you spent time for these useful suggestions and have a nice discussion with you.

**Comment by hunterliu1003** [comment]
I will consider all of these suggestions in the next BREAKING CHANGE of Vue Final Modal.

**Comment by hunterliu1003** [comment]
All the suggestions are implement in branch `v4`, and will be released very soon
