### ISSUE TITLE
Failing to implement vue-final-modal in a Nuxt _slug.vue template

### ISSUE THREAD

**Issue by rowild** [vue-final/vue-final-modal#146]
I wonder if this is the place where I can ask for support – if not, would anybody be so kind to direct me to the proper place? Thank you!

I have an `introduction` folder in `pages`, which has a dynamic `_slug.vue` template:

```
/pages
  /introduction
    /_slug.vue
    /index.vue
  introduction.vue
```

The various content elements that will be rendered in the dynamic `_slug` page will almost all have a video to be shown in a modal. Writing something like this works:

```html
<template>
  <section>
    <div v-if="content.video">

      <vue-final-modal v-model="showModal" name="video">
        <header>...</header>
        <video :src="`${strapiUrl}${content.video.video.url}`" preload="metadata"></video>
      </vue-final-modal>

      <button @click="openModalExample">Play Video</button>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      showModal: false
    }
  }
  methods: {
    openModalForVideo() {
      this.$vfm.show('video')
    } 
  }
}
</script>
```

In nuxt-config I followed the instructions given in the setup instructions:
https://vue-final-modal.org/setup#register-plugin-in-nuxt

But I have no idea how to integrate those features that come along with `modal-container` and VDynamicModal or the Tailwind Examples. There is no "App.vue" nor a "main.js" available in Nuxt, at least not in a regular nuxt-cli setup, which confuses the whole thing. Where to put `modal-container` then? In the default layout?  Or in the _slug template? Nuxt says it is not important to import components, but I keep getting errors all over the place, when I don't. So what is the proper approach to get e.g. VDynamicModal working?

Is there any chance that somebody could provide an example of how to do that?

Thank you!

**Comment by rowild** [comment]
Thank you very much, @hunterliu1003 , for this example! Very much appreciated!
I am still struggling with modals-global (in default layout) and calling a fullscreen modal from a _slug (e.g. sidebar) though... I will prepare and example and come back with a follow-up question, if that is all-right with you. leaving this issue open for the moment...

**Comment by hunterliu1003** [comment]
No problem. I don't mind keeping this issue open until solve your question.

**Comment by rowild** [comment]
I think I finally understood how this plugin works, at least to the amount that I can use it. Thank you! I will close this issue – hope this is ok with you!
