### ISSUE TITLE
Dynamic Model - Defining  the component as string like in the docs, fails silently

### ISSUE THREAD

**Issue by lsblsb** [vue-final/vue-final-modal#148]
### Version

vue-final-modal: 3.4.0
vue: 3.0.0

### OS

Ubuntu 20.04 on Windows 10 WSL2

### Steps to reproduce

Use VueFinalModal 3.4.0 with Vue 3.0.0 and rebuild the example shown here (docs v3.4.0):

https://v3.vue-final-modal.org/dynamic-modal

### What is Expected?

A working copy of the example

### What is actually happening?

An plain html element with the name of the dynamic component is created inside the modals-container.
No error is generated.

#### change this part as follows: https://v3.vue-final-modal.org/dynamic-modal#basic ####

```
import VDynamicModal from "@/components/VDynamicModal.vue" // currently working code

<script>
export default {
  methods: {
    dynamic() {
      this.$vfm.show({
        /* component: 'VDynamicModal' // original example code */
        component: VDynamicModal // currently working code
      })
    }
  }
}
</script>
```

**Comment by hunterliu1003** [comment]
@lsblsb 
If using String in  component

```js
<script>
export default {
  methods: {
    dynamic() {
      this.$vfm.show({
        component: 'VDynamicModal'
      })
    }
  }
}
</script>
```

you must register the `VDynamicModal` component somewhere else, like globally register component in `main.js`

```js
import { createApp } from 'vue'
import App from '@/App.vue'
import VDynamicModal from '@/components/VDynamicModal.vue'

const app = createApp(App)
app.component('VDynamicModal', VDynamicModal)
```

**Comment by lsblsb** [comment]
@hunterliu1003
Thanks! As a beginner, i missed that fact in the mentioned documention - especially due to the lack of an error.
