### ISSUE TITLE
Typings is different with the document

### ISSUE THREAD

**Issue by 8bu** [vue-final/vue-final-modal#149]
### Version

vue-final-modal: v3.4.0
vue: v3.1.5 with vite v2.4.4
typescript: v4.3.5

### OS
Windows

### Reproduction link
![image](https://user-images.githubusercontent.com/23427728/128765286-bf3aee2e-97a9-40e4-ac6d-e8694608c7bb.png)

### Steps to reproduce
N/A

### What is Expected?
More specific installation steps for Vue 3 & Typescript. Current document is really confusing

### What is actually happening?
![image](https://user-images.githubusercontent.com/23427728/128765611-d5681fcb-813b-478c-8352-beea578092b0.png)

This is not correct syntax to use with Vue 3 & Typescript. And I can't really install & use this package for my project because of the types was wrong & many compile errors.

**Comment by 8bu** [comment]
I just read v2 docs and the document is about the same & not updated to fit with V3.

**Comment by diegozavaletatelanto** [comment]
Same issue, im trying to setup, i cannot setup in a local component :(

**Comment by riderx** [comment]
@hunterliu1003 hey can we have a bit of context of why not planned ?

**Comment by hunterliu1003** [comment]
> @hunterliu1003 hey can we have a bit of context of why not planned ?

Because the vue-final-modal@4.x will rewrite with TS, it will be released very soon.
I'm working on the new version of the documentation

**Comment by riderx** [comment]
thanks a lot, that make sense !
