### ISSUE TITLE
Makes a mistake that doesn't make sense...

### ISSUE THREAD

**Issue by Pronicio** [vue-final/vue-final-modal#160]
Hello, I am on vue 3 and I try to initialize the module but there is an error : https://i.imgur.com/xOHafcm.png
Here is my code:
```js
import { createApp } from 'vue'
import App from './App.vue'

import { vfmPlugin } from 'vue-final-modal'

createApp(App)
  .use(vfmPlugin) 
  .mount('#app');
```
I just inserted it in main.js and the app won't launch.  
Full app here : https://replit.com/@Pronicio/VueMondal
Thank you.

**Comment by hunterliu1003** [comment]
Hello

```js
import { createApp } from 'vue'
import App from './App.vue'

import { vfmPlugin } from 'vue-final-modal'

createApp(App)
  .use(vfmPlugin()) 
  .mount('#app');
```

**Comment by Pronicio** [comment]
It doesn't work either, but I think it comes from repl.it because if I run it locally it works fine.
