### ISSUE TITLE
max-width not working

### ISSUE THREAD

**Issue by lordenas** [vue-final/vue-final-modal#168]
### Version
vue-final-modal: 3.4.1
vue: v3.0.0

### OS
Mac 

### Reproduction Link
https://vue-final-modal.org/examples/liveDemo

### Steps to reproduce
try setting max-width property.
It will be ignored. 

### What is Expected?
limiting the window width 

### What is actually happening?
The window stretches to fit the width of the content 

I am trying to limit the width of the window. I set the "max-width" property. But the window is still stretched across the width of the content.

**Comment by hunterliu1003** [comment]
Hi @lordenas 
the prop max-width is only work for drag and resize modal.
If you need to set a max-width to limit the modal content, you can bind classes to content-class or styles to content-style
