### ISSUE TITLE
Dynamic modal not working with Nuxt 2.5

### ISSUE THREAD

**Issue by rowild** [vue-final/vue-final-modal#176]
### Version

vue-final-modal: v2.4.1
vue: v2.6.1? (the one coming along with Nuxt v2.15.8)
nuxt: v2.15.8
OS: Mac Catalina, Chrome, Codesandbox

### Reproduction Link

https://codesandbox.io/s/keen-pond-qitoz?file=/nuxt.config.js

This Codesandbox tries to rebuild the "Basic Dynamic Modal Example" as described here:
https://vue-final-modal.org/dynamic-modal/#basic

Only difference: It is a Nuxt app.

Result: It does not work (and I think I have covered all the steps appropriately). Why?

**Comment by hunterliu1003** [comment]
Hi @rowild ,

This is a working version, please take a look: 
https://codesandbox.io/s/vue-final-modal-dynamic-modal-forked-vel7i

I remove the `ModalsContainer` in `page/index.vue` because ModalsContainer was globally registered by `plugin/vue-final-modal.js`

REMOVE:
```
import { ModalsContainer } from "vue-final-modal";

export default {
  components: {
    ModalsContainer
  }
}
```

ADD:
in nuxt.config.js
```
  plugins: [
    {
      src: "~/plugins/vue-final-modal.js"
    }
  ],
  build: {
    transpile: ["vue-final-modal"]
  },
```

**Comment by rowild** [comment]
Hi, @hunterliu1003 ! Thank you for your example and response! Highly appreciated!

I think the documentation should mention that components have to be registered:

```js
Vue.component("VDynamicModal", VDynamicModal);
```

This is vital information, especially when it comes to dynamic modals! And not reading about it in the docu leaves users lost in space... It is not enough to provide examples (even though that's great). (Or in case it is somewhere in the docu, it has to be made way more visible!)

**Comment by rowild** [comment]
@hunterliu1003 What are you thoughts about improving the docu? I would provide a PR, but only if you agree.

**Comment by hunterliu1003** [comment]
I think register a component before using it is instinct to a Vue developer. So the docs didn't mention it. 

I agree with you that the docs of VFM should be improved. If you are willing to help, you can try to improve the docs in https://vue-final-modal.org/dynamic-modal/. (Or anywhere you think better). then I will merge the PR thanks.

**Comment by rowild** [comment]
@hunterliu1003 You are very right, but on the other hand Nuxt has an option that allows automatic component registration. This seems to be very common, so in Nuxt it can happen that people (like me) forget to register components... I will provide a PR, maybe you can need it, let's see :-)
Thank you!

**Comment by hunterliu1003** [comment]
Cool!

> Nuxt has an option that allows automatic component registration.

I really love automatic component registration too. it's super convenience for lazy people (like me) and it also make the SFC much clean in my opinion
