### ISSUE TITLE
Dynamic Modal not working with vue3

### ISSUE THREAD

**Issue by jokrah** [vue-final/vue-final-modal#182]
### Version

vue-final-modal: v3.4.3
vue: v3.2.20

### OS

Mac

### Steps to reproduce
Using $vfm.show(dynamicModalOptions, params) with vue3 shows the following warnings and no modal is shown. The same code was working for vue3 with combat. But after transitioning to vue3 it's not working anymore.

`runtime-core.esm-bundler.js:6568 [Vue warn]: Invalid VNode type: undefined (undefined) `
and
`Unhandled error during execution of mounted hook`

### What is Expected?

No warnings and modal is shown

### Link for reproducing 

https://codesandbox.io/s/sharp-yalow-uiu82

**Comment by xaja** [comment]
https://codesandbox.io/s/adoring-turing-9ygwv
a lot of differences

1. in main.js you must add component
2. in app.vue no need to import and register modals-container
3. in simple-modal.vue no need to import and register vue-final-modal

**Comment by jokrah** [comment]
Thanks a lot! It was indeed the problem that I imported and registered vue-final-modal and the modals-container unnecessarily.
