### ISSUE TITLE
dynamic component not work

### ISSUE THREAD

**Issue by RezaErfani67** [vue-final/vue-final-modal#184]
### Version
vue-final-modal: 2.4.1
vue:  v2.6.14

### OS
Windows

### Steps to reproduce
click on button for showing component but return any thing...
when i add console.log(  this.$vfm.show(edit,{itemID :"..."})) return Promise

### What is Expected?
show component on modal

### What is actually happening?
```javascript
<template>
 <button @click.prevent="openEditModal(item._id,item.title)" >Edit</button>
</template>
<script>
    import edit from './edit.vue'
     components: {    edit   },
      methods:{
       openEditModal(hrmApplicantID) {
                      this.$vfm.show(edit,{itemID :"..."});
                  },
      }
</script>
```

**Comment by hunterliu1003** [comment]
@RezaErfani67 please read docs here https://vue-final-modal.org/dynamic-modal#vfmshowdynamicmodaloptions-params about dynamicModalOptions structure.

Try
```js
$vfm.show({
    slots: {
        default: {
            component: edit,
            bind: {
                itemID: "...."
            }
        }
    }
})
```
