### ISSUE TITLE
How to use params in modal?

### ISSUE THREAD

**Issue by rowild** [vue-final/vue-final-modal#185]
This part in the docu talks about how to use "params":
https://vue-final-modal.org/guide/params

However, the first part describes an assignment: `event => event.ref.params`, but there is not further description on how to access `events`. 

Also, how does a `$vfm.show('stackable', { test: 123 })` translate to the object API?

```js
this.$vfm.show({
	component: 'stackable',
	params: cues, /// <== Like this?
	slots: { [...] },
})
```

Can you please provide a better description with a better example? Thank you!

**Comment by hunterliu1003** [comment]
Hi @rowild,
there is docs: https://vue-final-modal.org/dynamic-modal#vfmshowdynamicmodaloptions-params

```
this.$vfm.show(
    {
	component: 'stackable',
	slots: { [...] },
    },
    {
        ...params // <== Like this
    }
)
```

**Comment by rowild** [comment]
@hunterliu1003 thank for your response!

Your plugin is great, has tons of functionality and seems to be very flexible, but ... no offense, it is absolutely NOT clear how to use "params". It might be clear to you, since you developed this plugin, but as someone who what to use your plugin, this is simply not a user-friendly guide. Please compare with the Vue docu which has tons of examples.

Even though you say there is docu available, you do not show how to access params in the template or in "mounted" or "methods" or where ever. I still do not know how to use "params". Please provide a GOOD example that shows.

I'd love to contribute, but since I do not know how to successfully create modals, I can't, at least not with this case. So I ask you kindly to improve the docu!
