### ISSUE TITLE
How can a modal be closed, when the route / browserHistory changes?

### ISSUE THREAD

**Issue by rowild** [vue-final/vue-final-modal#188]
If a modal is currently opened and the user decides to click the browser back button - how can the modal be closed?

**Comment by rowild** [comment]
@hunterliu1003 Any chance you could give me a hint? Thanks!

**Comment by sevenmay** [comment]
@rowild Have you tried `$vfm.hideAll()` in `router.beforeEach`?

**Comment by rowild** [comment]
@sevenmay No, but I will try right away! Thank you! :-)

**Comment by rowild** [comment]
@sevenmay I am in a nuxt app where navigation guards are defined in a middleware. That middleware function has access to context, but it seems context does not contain $vfm. I console.logged context and digged through the whole object - but to no avail. 
Any idea how to solve this?

**Comment by sevenmay** [comment]
I don't use nuxt but $vfm is a singleton (at least in v3.4.3) so you should be able to import and use it everywhere.

```
import { $vfm } from 'vue-final-modal';
$vfm.hideAll();
```

**Comment by rowild** [comment]
Thank you again, @sevenmay !

I know that you do not use Nuxt, but I leave my experience anyway. Who knows, maybe you find a bug anyway. :-)

I tried this, which does not work. But what troubles mere is, that with each click on the browser's back button, the counter increases drastically. While beforeEach is called twice on the first click on the back button, it is called 5 times on the second click and ... well, many more on the third. That keeps on going. Does not seem to be a good idea to use middleware for navigation guards in Nuxt.

```js
import { $vfm } from 'vue-final-modal';
let counter = 0

export default function ({ store }) {
  store.app.router.beforeEach((to, from, next) => {
    console.log("Router middelware closeModals: ", counter++)
    $vfm.hideAll()
    next()
  })
}
```

BTW: I embedded all my modals using the "dynamic modals" technique.

**Comment by rowild** [comment]
A watcher seems to work fine:

```js
watch: {
	$route(newVal) {
		this.$vfm.hideAll()
	},
}
```

I put this script in the top default layout file and it does its job.

If there is a better solution, please add one, @hunterliu1003 ! Thank you!

**Comment by hunterliu1003** [comment]
No I still have no idea for connection between vue-final-modal and vue-router (or window.history)

**Comment by rowild** [comment]
@hunterliu1003 Ok, thank you for your feedback! :-)
