### ISSUE TITLE
Wrong typescript type for dynamic modals

### ISSUE THREAD

**Issue by manuelmazzuola** [vue-final/vue-final-modal#189]
For dynamic modals the return type is a Promise

The returned typescript type is void https://github.com/vue-final/vue-final-modal/blob/fc0b938838710cac475f1de6587175c74c41722c/types/index.d.ts#L72

**Comment by hunterliu1003** [comment]
@manuelmazzuola 

Sorry I'm not an Typescript user actually, and I'm still learning it. I would be very grateful if you can send a PR to fix this.

**Comment by hunterliu1003** [comment]
fixed in [v2.4.3](https://www.npmjs.com/package/vue-final-modal/v/2.4.3)
fixed in [v3.4.7](https://www.npmjs.com/package/vue-final-modal/v/3.4.7)
