### ISSUE TITLE
The modal changes position on resize 

### ISSUE THREAD

**Issue by adamwuss** [vue-final/vue-final-modal#192]
### Version

vue-final-modal: v3.4.3
vue: 3.0.0

###System

Linux Ubuntu v 20.04.3

### Reproduction Link
https://codesandbox.io/s/delicate-hooks-emt99?file=/src/App.vue

### Steps to reproduce
1. Create example vue final modal
2. Change resize properties to true
3. Try to resize 

### What is Expected?
When I resize, the modal component should stay in one position

### What is actually happening?
When I resize the modal changes position to the same side

**Comment by hunterliu1003** [comment]
@adamwuss 

Thanks for your feedback

Here is a temperal workable example if you need.
https://codesandbox.io/s/loving-jennings-iwudn

I will try to fix this, but after some main feature released recently
