### ISSUE TITLE
How to watch for openedModals?

### ISSUE THREAD

**Issue by xaja** [vue-final/vue-final-modal#194]
Hello and thanks for a great product!

Have a question: 
In component i want to know — is there any opened modals.
in docs i find https://v3.vue-final-modal.org/api#vfmopenedmodals but how can i `watch` for this?

**Comment by hunterliu1003** [comment]
Currently `openedModals` is a Array, so it's not allow to watch for it, you can check the `openedModals.length` anytime.
I don't think it's required for watch `openedModals`.
If you need this feature, please reopen the issue
