### ISSUE TITLE
我嘗試使用用nuxt3  來安裝但一直有問題

### ISSUE THREAD

**Issue by jannyjie** [vue-final/vue-final-modal#197]
https://vue-final-modal.org/setup

使用你提供  nuxt.config.js  的方法加上去有問題 但我也有嘗試適用 nuxt3 引入的方法也是不行

### Version

vue-final-modal: 
vue: 
nuxt: 

### OS

Mac or Windows

**Comment by jannyjie** [comment]
// plugins  放在這裡 （全域註冊）

import { defineNuxtPlugin } from '#app';
import { vfmPlugin } from 'vue-final-modal';
export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(vfmPlugin);
});

**Comment by lih1989** [comment]
nuxt: 3.0.0-rc.8

plugin-name.ts
```
import { defineNuxtPlugin } from '#app'
// @ts-ignore
import { vfmPlugin } from 'vue-final-modal/lib'
export default defineNuxtPlugin((nuxtApp: any) => {
  nuxtApp.vueApp.use(vfmPlugin)
})
```

nuxt.config.ts
```
export default defineNuxtConfig({
  ...
  buildModules: [
    ...
    'vue-final-modal'
  ],
  ...
})
```

**Comment by gabrielfelipecsk** [comment]
> nuxt: 3.0.0-rc.8
> 
> plugin-name.ts
> 
> ```
> import { defineNuxtPlugin } from '#app'
> // @ts-ignore
> import { vfmPlugin } from 'vue-final-modal/lib'
> export default defineNuxtPlugin((nuxtApp: any) => {
>   nuxtApp.vueApp.use(vfmPlugin)
> })
> ```
> 
> nuxt.config.ts
> 
> ```
> export default defineNuxtConfig({
>   ...
>   buildModules: [
>     ...
>     'vue-final-modal'
>   ],
>   ...
> })
> ```

thanks
