### ISSUE TITLE
please show example usage of vue 3 setup

### ISSUE THREAD

**Issue by myomyintaung1411** [vue-final/vue-final-modal#198]

**Comment by diegozavaletatelanto** [comment]
Yes, please, we really appreciate it if you update your documentation with **Vue 3** and **Typescript** Setup 👍🏼

**Comment by hunterliu1003** [comment]
Please checkout
https://v3.vue-final-modal.org/setup#global-register-plugin
https://codepen.io/hunterliu1003/pen/KKedVKp
https://codepen.io/hunterliu1003/pen/OJmNxmB
