### ISSUE TITLE
Closing a dynamic modal throws error: enableBodyScroll unsuccessful

### ISSUE THREAD

**Issue by jifka** [vue-final/vue-final-modal#203]
In the browser console, closing a dynamic modal always throws the error:

enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS device

Environment:
Vue3 - globally registered vue-final-modal so calling this.$vfm.show works everywhere
Chrome

The dynamic modal component (MyDialog) is just a vanilla component with just HTML in the template text:
```
<template>
  <div>HELO WERLD</div>
</template>
```

The modal is opened with:
this.$vfm.show({component:MyDialog})

Closing is done by clicking on the coverall background.

**Comment by pommedepain** [comment]
+1

**Comment by jairoblatt** [comment]
+2

**Comment by Iviyan** [comment]
I get the same error when I close the modal window and go to another route (the view in which the modal window was destroyed).
If I add a delay of 300 ms before the transition, there is no error.

**Comment by AnatoliiDev** [comment]
+1

**Comment by Shade465** [comment]
+1

**Comment by nmarsh92** [comment]
@Iviyan 
`$vfm.hideAll()` returns a promise, if you wait for the promise to resolve before switching routes you won't get this error.
