### ISSUE TITLE
Dynamic modal mounted() firing twice

### ISSUE THREAD

**Issue by jifka** [vue-final/vue-final-modal#204]
### Version

vue-final-modal: latest
vue: 3

### OS

Windows

### Steps to reproduce

Created a dynamic modal and opened it with $vfm.show({component:myModal})

In myModal, the mounted event hook fires twice. Looking at the DOM, the modal is only there once.

**Comment by hunterliu1003** [comment]
I check the behavior in v3.4.8, the mounted hook only emit once
