### ISSUE TITLE
Prevent click not working

### ISSUE THREAD

**Issue by cm-tigeen** [vue-final/vue-final-modal#210]
### Version

vue-final-modal: v3.4.3
vue: v3.2.31
npm: 8.5.0
node: 16.14.2

### OS
Windows

It is not working prevent click prop and attachment refers for your reference. If prevent click enable, i can able to click outside.

Can you have two modals with prevent click example?

![vue-final-modal_error](https://user-images.githubusercontent.com/77827545/160098350-2538dac6-ee88-490c-abce-2bf77ee506d3.png)

Thank you,
N Chandra Mohan,
Tech Lead Web & Mobile Development,
Tigeen Computing Pvt Ltd.

**Comment by hunterliu1003** [comment]
You have to set `:preventClick="true"` to all opened modals
