### ISSUE TITLE
Nuxt 3 RC - dynamic modal doesn't open

### ISSUE THREAD

**Issue by mnlj** [vue-final/vue-final-modal#221]
I'm trying to use dynamic modal on the latest Nuxt 3 RC1 with default Vite builder and I'm running into a problem. Looking at it in the devtools, the new dynamic modal appears to be added into ModalsContainer `dynamicModals` array, but it's not rendered. I've created small reproduction repo below. I've been using previously using it in nuxt 3 beta with webpack builder just fine (using vfmPlugin in nuxt plugins and more polished code). Does anyone have any ideas please?

### Version

vue-final-modal: 3.4.3
vue: 3.2.33
nuxt: 3.0.0-rc.1

### OS
Windows

### Reproduction Link
https://github.com/mnlj/nuxt-vue-final-modal

### Steps to reproduce
Reproduction repo, npm install, npm run dev, click the button on the page.

### What is Expected?
Modal shows up

### What is actually happening?
Modal doesn't show up

**Comment by dmitryT93** [comment]
same problem

**Comment by hunterliu1003** [comment]
Vue Final Modal [v4.0.0-beta-3](https://www.npmjs.com/package/vue-final-modal/v/4.0.0-beta.3) is in beta and support nuxt 3
https://v4.vue-final-modal.org

**Comment by hunterliu1003** [comment]
feel free to reopen if the issue still exist
