### ISSUE TITLE
Mistake in documentation for beforeOpen event

### ISSUE THREAD

**Issue by victor-ponamariov** [vue-final/vue-final-modal#227]
In https://vue-final-modal.org/guide/params documentation is says the event name is `beforeOpen`, but for me it works only if it's called `before-open`.

E.g.

```
<template>
  <vue-final-modal
    v-bind="$attrs"
    classes="modal-container"
    content-class="modal-content"
    v-on="$listeners"
    @before-open="onBeforeOpen" <-- Only this way the event works, not @beforeOpen
  >
    <span class="modal__title">Hello, vue-final-modal</span>
    <div class="modal__content">
      <p>Vue Final Modal is a renderless, stackable, detachable and lightweight modal component.</p>
    </div>
  </vue-final-modal>
</template>
```

Looks like a bug in documentation, or I'm missing something

**Comment by victor-ponamariov** [comment]
Also I'm not sure but I cannot access passed params to dynamic modals.

Here is the event handler:

```
<script>
import { VueFinalModal } from 'vue-final-modal'

export default {
  components: {
    VueFinalModal
  },

  inheritAttrs: false,

  methods: {
    onBeforeOpen (event) {
      console.log('onBeforeOpen event', event) 
      console.log('params', event.ref.params)
    }
  }
}
</script>
```

When I check the console.log output, in the event (the first output) I can find them under `event.ref.params`. But the second output doesn't have these params, they magically disappear. Why so?

**Comment by Maizerer** [comment]
@victor-ponamariov You are right, there is a mistake in the documentation. It also worked for me `@before-open`

Try passing params to the function in this way:
`@before-open="(e) => initParams(e)"`

```
initParams(event) {
      console.log('onBeforeOpen event', event) 
      console.log('params', event.ref.params)
},
```
This is works for me
