### ISSUE TITLE
Bootstrap usage

### ISSUE THREAD

**Issue by odion-cloud** [vue-final/vue-final-modal#229]
### Version

vue-final-modal: "^2.4.1"
vue:  v2.6.12

when i use this modal on my bootstrap project it those not  display properly with the width and height,
is there any bootstrap usage i can work with?

**Comment by hunterliu1003** [comment]
You have to define the style yourself for VueFinalModal.
Please follow the steps https://v2.vue-final-modal.org/examples/stepByStep#custom-the-modal-style
