### ISSUE TITLE
Console warning about $listeners and v-on

### ISSUE THREAD

**Issue by ariona** [vue-final/vue-final-modal#231]
### Version

vue-final-modal: 3.4.4
vue: 3.2.36

### OS

Mac

### Reproduction Link
https://codesandbox.io/s/cranky-hill-91cpl6?file=/src/App.vue

### Steps to reproduce
1. Create custom modal,
2. Call modal using $vfm.show method

### What is Expected?
No warning from vue

### What is actually happening?
Console show some warning like below

```
[Vue warn]: Property "$listeners" was accessed during render but is not defined on instance. 
  at <CustomModal key= Symbol(dynamicModal) title="Are you sure?" content="Template \"Template 1\" will be removed"  ... > 
  at <ModalsContainer> 
  at <App>

[Vue warn]: v-on with no argument expects an object value. 
  at <CustomModal key= Symbol(dynamicModal) title="Are you sure?" content="Template \"Template 1\" will be removed"  ... > 
  at <ModalsContainer> 
  at <App>
```

**Comment by hunterliu1003** [comment]
`$listeners` is removed in vue 3
https://v3-migration.vuejs.org/breaking-changes/listeners-removed.html

**Comment by ariona** [comment]
I see, thanks for the reference. solved by removing `v-on="$listeners"` on my custom-modal

I am just following the documentation of final modal, it need an update for sure.
