### ISSUE TITLE
Firefox: attach + scroll-lock -> modal not scrolling into view

### ISSUE THREAD

**Issue by Eusebius1920** [vue-final/vue-final-modal#234]
### Version

vue-final-modal: v3.4.4
vue: 3.2.37

### OS

All OS, Firefox in Version 102 (among other versions)

### Reproduction Link
https://codesandbox.io/s/gifted-merkle-z1j9c0?file=/src/App.vue

works on chrome, not on firefox

### Steps to reproduce
click on the button "open model" at the bottom of the page

### What is Expected?
modal opens and its content is visible

### What is actually happening?
modal opens and content is not visible / scrolled into view and there is no possibility to scroll for the user (because scroll lock is enabled by default)

### Solution
After [line 397 in VueFinalModal.vue](https://github.com/vue-final/vue-final-modal/blob/a258019a6466648f906482ebc60747145a9409ee/lib/VueFinalModal.vue#L397) add something like

```javascript
if (props.focusRetain || props.focusTrap) {
  vfmContainer.value.focus()        
  if(vfmContainer?.value?.scrollIntoView) vfmContainer.value.scrollIntoView()
}
```

**Comment by Eusebius1920** [comment]
I guess [line 331](https://github.com/vue-final/vue-final-modal/blob/a258019a6466648f906482ebc60747145a9409ee/lib/VueFinalModal.vue#L331) has to be adjusted accordingly

I can prepare a pull request if confirmed and desired

**Comment by hunterliu1003** [comment]
@Eusebius1920 

I think it's the style issue. I set the vfm position from `absolute` to `fixed` solved the issue
https://codesandbox.io/s/ecstatic-voice-pbolot?file=/src/App.vue:949-987
```css
.vfm {
  position: fixed !important;
}
```
