### ISSUE TITLE
Update transition documentation for vue3

### ISSUE THREAD

**Issue by karltbone** [vue-final/vue-final-modal#237]
Hello, 

https://vue-final-modal.org/guide/properties#transition

In vue3, the names of the transition classes have changed. May be good to have an example for vue3.

Current doc (Show example transition Object): 
```
:transition="{
      'enter-active-class': 'transition duration-200 ease-in-out transform',
      'enter-class': 'translate-y-full',
      'enter-to-class': 'translate-y-0',
      'leave-active-class': 'transition duration-200 ease-in-out transform',
      'leave-to-class': 'translate-y-full',
      'leave-class': 'translate-y-0'
    }"
```

What I found to work in vue3: 
```
:transition="{
      'enter-active-class': 'transition duration-200 ease-in-out transform',
      'enter-from-class': 'translate-y-full',
      'enter-to-class': 'translate-y-0',
      'leave-active-class': 'transition duration-200 ease-in-out transform',
      'leave-to-class': 'translate-y-full',
      'leave-from-class': 'translate-y-0'
    }"
```

Thank you

**Comment by db-conception** [comment]
> 'enter-active-class': 'transition duration-200 ease-in-out transform',
>       'enter-from-class': 'translate-y-full',
>       'enter-to-class': 'translate-y-0',
>       'leave-active-class': 'transition duration-200 ease-in-out transform',
>       'leave-to-class': 'translate-y-full',
>       'leave-from-class': 'translate-y-0'

Hello
It doesn't work at me. Did you change anything else ? 
The modal should translate from top exact ?

**Comment by db-conception** [comment]
> Hello,
> 
> https://vue-final-modal.org/guide/properties#transition
> 
> In vue3, the names of the transition classes have changed. May be good to have an example for vue3.
> 
> Current doc (Show example transition Object):
> 
> ```
> :transition="{
>       'enter-active-class': 'transition duration-200 ease-in-out transform',
>       'enter-class': 'translate-y-full',
>       'enter-to-class': 'translate-y-0',
>       'leave-active-class': 'transition duration-200 ease-in-out transform',
>       'leave-to-class': 'translate-y-full',
>       'leave-class': 'translate-y-0'
>     }"
> ```
> 
> What I found to work in vue3:
> 
> ```
> :transition="{
>       'enter-active-class': 'transition duration-200 ease-in-out transform',
>       'enter-from-class': 'translate-y-full',
>       'enter-to-class': 'translate-y-0',
>       'leave-active-class': 'transition duration-200 ease-in-out transform',
>       'leave-to-class': 'translate-y-full',
>       'leave-from-class': 'translate-y-0'
>     }"
> ```
> 
> Thank you

Did you add css ?

**Comment by hunterliu1003** [comment]
Thanks! The documentation was updated.

**Comment by gsabater** [comment]
I'm here to say that i haven't seen anything regarding transitions in the documentation (at least at the website), and the comment @db-conception worked perfectly for me.

I think that the website should display an example of it.
