### ISSUE TITLE
How to completely remove from the dom..??

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [vue-final/vue-final-modal#240]
### Version

vue-final-modal: 3.4.4
vue: 3.x

### OS

Ubuntu

### What is Expected?
Want to completely remove from dom.

### What is actually happening?
It just adds `display:none` not removed from the dom, how can I?

**Comment by valh1996** [comment]
@ShekhSaifuddin007 Why not simply use a `v-if` directive to remove it?

**Comment by hunterliu1003** [comment]
Please try to set `:ssr="false"` to use `v-if` internally [ssr prop](https://v3.vue-final-modal.org/guide/properties#ssr)

I think `ssr` prop is a bad name, so it will be rename to `display-directive` from vue-final-modal@v4
