### ISSUE TITLE
can't resolve a function in CDN

### ISSUE THREAD

**Issue by tsuvic** [vue-final/vue-final-modal#242]
### Version
vue-final-modal: v3.3.1
vue: 3.2.25

### OS
MacOS 

### Steps to reproduce
Followed setup manual(https://vue-final-modal.org/setup),
and putting "<script src="https://cdn.jsdelivr.net/npm/vue-final-modal"></script>" in HTML directly,
then putting source following setup manual's demo code.

"
html
 head
    <script type="importmap">
        {
          "imports": {
            "vue": "https://unpkg.com/vue@3/dist/vue.esm-browser.js"
          }
        }
    </script>
 /head

 body
  <div id="app">

    <button @click="showModal = true">
      Simple
    </button>

    <vue-final-modal
      v-model="showModal"
      classes="modal-container"
      content-class="modal-content"
    >
      <span># Simple modal</span>
      <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry.
      </p>

      <button class="modal-close" @click="showModal = false">
        x
      </button>

     </vue-final-modal>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/vue-router@4.0.5/dist/vue-router.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-final-modal"></script>

    <script type="module">
        import {createApp} from 'vue'
        import { vfmPlugin } from 'vue-final-modal'
        const app = createApp(app)
        app.use(vmfPlugin)
        app.mount('#app')
    </script>
 /body
/html
"

### What is Expected?
no error, and displaying like sample code below. 
https://codepen.io/hunterliu1003/pen/ZEWoYeE

### What is actually happening?
I got error below on chrome, and cant call function in vue-final-modal library.

"
Uncaught TypeError: i.default.observable is not a function
    at ee (vue-final-modal:5:24243)
    at vue-final-modal:5:25500
    at vue-final-modal:5:161
    at vue-final-modal:5:241
ee @ vue-final-modal:5
(anonymous) @ vue-final-modal:5
(anonymous) @ vue-final-modal:5
(anonymous) @ vue-final-modal:5
"

before putting code which is related to vue-final-modal, it works well.

**Comment by hunterliu1003** [comment]
Please checkout this example for Vue 3
https://codepen.io/hunterliu1003/pen/KKedVKp

You might use the wrong CDN link, you have to add `next` tag or specific version
`https://unpkg.com/vue-final-modal@next`
