### ISSUE TITLE
Can't bind modelValue

### ISSUE THREAD

**Issue by jwensley2** [vue-final/vue-final-modal#248]
### Version

vue-final-modal: 3.4.4
vue: 3.2.39

### Steps to reproduce
```js
$vfm.show({
    component: MyComponent,
    bind: {
        modelValue: ['a', 'b', 'c'],
    },
});
```

### What is Expected?
The modelValue should be passed to MyComponent

### What is actually happening?
The wrong value is being passed in, MyComponent is receiving `true` instead of `['a', 'b', 'c']`

**Comment by hunterliu1003** [comment]
`modelValue` is only allow boolean type for a modal component.

Please checkout the advanced example for `$vfm.show` https://v3.vue-final-modal.org/dynamic-modal#advanced
