### ISSUE TITLE
Scroll blocking doesn't work on ios(safari)

### ISSUE THREAD

**Issue by KoiLVeD** [vue-final/vue-final-modal#25]
### Version 
vue-final-modal: v0.19.0
vue: v2.6.12

### OS
Mac

mobile Safari ignores the overflow:hidden on the body.
You should use the scroll lock hack.

**Comment by hunterliu1003** [comment]
Thanks for your feedback.

I currently don't have better way, do you have any suggestion to hack scroll lock in mobile Safari?

I found [body-scroll-lock](https://www.google.com/search?q=body+scroll+lock&rlz=1C5CHFA_enTW885TW889&oq=body+scroll+lock&aqs=chrome..69i57j35i39l2j0l2j69i60l3.5799j0j7&sourceid=chrome&ie=UTF-8)

**Comment by gfd6th** [comment]
I have the same issue on ios/chrome

**Comment by hunterliu1003** [comment]
Hi @gfd6th ,
Please try upgrade to the latest version `v0.21.3`

**Comment by gfd6th** [comment]
@hunterliu1003 
我的目前版本是 v0.21.3,
我不清楚我的问题是否和#1 的一样, 
我的问题是激活modal 后, 在 ios 的 chrome 浏览器上无法锁定滚动.
我自己目前已经通过  body-scroll-lock 插件实现.

```javascript
<vue-final-modal
      ref="vfm"
      @opened="onOpened"
      @before-close="onBeforeClosed"
    >
 ....
<vue-final-modal>

onOpened() {
      disableBodyScroll(this.$refs.vfm)
    },
    onClosed() {
      enableBodyScroll(this.$refs.vfm)
    },
```

**Comment by hunterliu1003** [comment]
Hi @gfd6th 

感謝你的回報，我也發現在 iOS chrome 有這個問題，我會再修正一個版本

**Comment by hunterliu1003** [comment]
Hi @gfd6th ,

This bugfix is published at:

- `0.21.4` for Vue 2
- `1.8.5` for Vue 3

**Comment by gfd6th** [comment]
@hunterliu1003 Thanks~
