### ISSUE TITLE
How to change click-to-close event ?

### ISSUE THREAD

**Issue by evdevru** [vue-final/vue-final-modal#250]
I have modal with interactive elements for copy. Im select text with nouse over modal, then modal closed - its not right. Can i change event from "mouse up" to "mouse down" on overlay ?

**Comment by hunterliu1003** [comment]
```
Can i change event from "mouse up" to "mouse down" on overlay ?
```
No, vue-final-modal didn't provide a way to change the event from `mouse up` to `mouse down`. And I don't understand the reason why you need that.
I'm not sure if I understand correctly with you question.
Can you provide reproduction or video?

**Comment by hunterliu1003** [comment]
Feel free to reopen if your question still exist.
