### ISSUE TITLE
Modal closes while dragging the scrollbar of its container with a mouse

### ISSUE THREAD

**Issue by J-Michalek** [vue-final/vue-final-modal#251]
### Version

vue-final-modal: v2.4.1 
vue: v2.7.10

### OS

Mac

### Reproduction Link
https://codesandbox.io/s/vigilant-sunset-3zblr8?file=/src/App.vue
### Steps to reproduce
1. Create a modal that is closable on click
2. Make it scrollable by setting overflow-y: scroll on .vfm__container
3. Try scrolling the content by dragging the scrollbar with your mouse

### What is Expected?
The modal to not close.

### What is actually happening?
The modal closes.

**Comment by hunterliu1003** [comment]
Please try to add overflow to `.vfm .vfm__content`
https://codesandbox.io/s/vigorous-smoke-fvhx1s?file=/src/App.vue:515-571
