### ISSUE TITLE
When the DRAG is turned on, How to set initial X and Y positions。

### ISSUE THREAD

**Issue by Soya-xy** [vue-final/vue-final-modal#252]
When the drag is turned on, How to set initial X and Y positions, it does not want to make it display in the middle

When I set top and left for drag:start and drag:move, I can't get drag and resize perfectly

### Version

vue-final-modal: 3.4.4
vue: 3.2.3

### OS

Mac

**Comment by hunterliu1003** [comment]
You can just override the initial style of `.vfm__content` to achieve this. For example:

```css
.vfm__content {
  top: 10px;
  left: 10px;
}
```
