### ISSUE TITLE
Is there any way to set the modal's position or offset of pageTop and pageLeft?

### ISSUE THREAD

**Issue by ChanXYan** [vue-final/vue-final-modal#255]
### Version

vue-final-modal: 3.4.4
vue: 3.2.37

### OS

Windows

### What is Expected?

When I use the dynamic way to show up a modal , I want to custom the modal position where it show up . I try to read documentation and codes in lib file , but I cant figure it out . 

sorry for my bad English and thanks for your hardwork in this project..

**Comment by hunterliu1003** [comment]
Hi @ChanXYan 
I can checkout the [Advance usage of dynamic modal](https://v3.vue-final-modal.org/dynamic-modal#advanced)
If you want to custom the modal position, you have to write the CSS your own because vue-final-modal is a styleless component.
You can also provide a codesandbox or jsfiddle.

**Comment by hunterliu1003** [comment]
feel free to reopen if your question is still exist
