### ISSUE TITLE
Initial size for resizable modals

### ISSUE THREAD

**Issue by volkerjaenisch** [vue-final/vue-final-modal#256]
### Is your feature request related to a problem? Please describe.
I am working with modals which show quite complex scientific charts. [Volcanic Ash monitoring system of the European Union](https://e-profile.eu/#/wp_profile) -> click on a chart icon. While migrating to vue3 we need a new modal and vue-final-modal is exactly what we are looking for. Thank you so much for coming up with so versatile a modal solution for Vuejs!
But we stumble on a minimal different behavior of vue-js-modal an vue-final-modal concerning the width and height attributes.
vue-js-modal is setting in any case the width/height attributes, vue-final-modal does this only after the first resizing.
This leads to confusion in our charts since we are not able to get a initial size of the modal programmatically. 
We are layering the 3D accelerated pixel engine Pixi (for the heatmap) with D3 SVG graphics and have the need to tell both layers absolute coordinates and bounding boxes to get too a visual match. Without the information of the width and height of the modal all HTML/CSS structures are not capable to determine their usable space.
In short words: vue-final-modal usually gets its width/height information from the content. In our case we need to set the modal size initially so that the HTML/CSS/JS inside can adjust its size to the boundary.

### Describe the solution you'd like
I forked vue-final-modal [https://github.com/Inqbus/vue-final-modal](https://github.com/Inqbus/vue-final-modal) and did a 10 line fix in the V3-Branch. With this fix the modal uses the min-Width and minHeight settings (if given) to set the modal size if "resizable" is set.
With this fix our quite complex modal works flawlessly with vue-final-modal. This is only a prove-of-concept but no solution. 

One may think off two props "initial_width", "initial_height" instead of abusing minWidth/Height which have their own relevant functionality. You are the masters of your code and may come up with a even better solution.

**The only relevant thing for our problem is that vue-final-modal has it actual width/height set when it is opened (And not only after the first resize).** This may even be a bug?

### Describe alternatives you've considered
I spend three weeks (no kidding :-( ) on this problem and found no other solution. I also conferred with other senior JS developers to no avail.
I simplify the findings of our joint afford with only one chart in the modal. [Example here](https://e-profile.eu/#/cm_profile) -> click on a chart icon. 
Our chart-DIV lives in the modal. The Chart-DIV is position:relative. Inside the chart-DIV there are only position:absolute DIVs (PIXI/SVG). We need position:absolute to match the two different graphic-engines in one plot. So the chart-DIV has no height of itself.
The chart-DIV is therefore set to height:"auto". 
If the enclosing width/weight is set the chart-DIV blows up to the boundary (modal) and we can get (programmatically in Vuejs) a defined size of the chart-DIV. 
If the enclosing width/weight is NOT set the chart-DIV collapses to height=0 and nothing goes.
The effect with vue-final-modal is : The charts are initial zero pixel in height. After the first resizing the charts are perfect.

### Additional context
I can come up with a JSfiddle to illustrate the problem if you like.

**Comment by ianoble** [comment]
Any chance this gets looked at? I'm having the same issue.

**Comment by DallasHoff** [comment]
I think Vue Final Modal does it this way to be as hands-off as possible when it comes to styling. The docs encourage you to use a higher-order component to wrap the VueFinalModal component. If you need to set the initial width and height of the modal, you can add props for this to your higher-order component (e.g. initialWidth and initialHeight) and then apply those to the modal with something like this.

```css
.vfm__content {
  width: v-bind(initialWidth);
  height: v-bind(initialHeight);
}
```

**Comment by ianoble** [comment]
Oh nice. For us, the VFM is in a HOC, so the new class override should hopefully work.

**Comment by ianoble** [comment]
Certainly could be doing something wrong, but after implementing your suggestion, it still doesn't appear to be any different than just setting height/width in the styles property. I can't resize the window.

![image](https://user-images.githubusercontent.com/7987064/202810982-9ae60209-d05c-406d-a241-c622d2a5a770.png)

**Comment by DallasHoff** [comment]
You are using !important which overrides the width and height VFM sets when you resize.
