### ISSUE TITLE
Problem with using dynamic modal. It seems to add up modals to container, but doesn't show.

### ISSUE THREAD

**Issue by flaczkiDomowe** [vue-final/vue-final-modal#258]
Hello. I have problem, as written in topic. I am using Laravel + Blade and at this momment I am migrating our project from 2 to 3. It's not single page application, that's why I find it rather difficult to move to vue 3. I created in my app.js file global function to create application with all required components and plugins. I have problem with using plugin $vfm. 

### Version

vue-final-modal: 3.4.4
vue: ^3.2.39
nuxt: I don't use 

### OS

Mac or **Windows**

### What is Expected?
On button click, there should appear CustomModal

### What is actually happening?
   console.log(this.$vfm.dynamicModals.length); is actually incrementing each time I click, but modal is not rendered.

![image](https://user-images.githubusercontent.com/57954182/199022040-2c675383-77b2-4764-a8cc-fa1ef341e6a1.png)

**Comment by hunterliu1003** [comment]
@flaczkiDomowe 
Do you missing the `<ModalsContainer />` in you `App.vue`
https://v3.vue-final-modal.org/dynamic-modal#prerequisite

**Comment by bradley-varol** [comment]
I have this same issue. Nuxt 2. I have added `<ModalsContainer />` to my layout. If console log `console.log(this.$vfm.dynamicModals.length)` after calling `this.$vfm.show({ component: MyImportedComponent })`, I can see the number incrementing.

**Comment by flaczkiDomowe** [comment]
> @flaczkiDomowe Do you missing the `<ModalsContainer />` in you `App.vue`? https://v3.vue-final-modal.org/dynamic-modal#prerequisite

Yes, I did. :(

**Comment by flaczkiDomowe** [comment]
Okay, let's get to the basics. I am using app.use($vfm) and app.component(ModalsContainer). Is it good way of doing that in Vue 3?

**Comment by hunterliu1003** [comment]
Please try

```js
// App.vue
import { vfmPlugin } from 'vue-final-modal'

App.use(vfmPlugin)
```

**Comment by flaczkiDomowe** [comment]
It doesn't work. 
`  <modals-container></modals-container>
<button @click="dynamicModalTest">I am button for testing Vue</button>`



`dynamicModalTest() {
                    console.log('test start');
                    this.$vfm.show({ component: 'CustomModal' });
                    console.log(this.$vfm.dynamicModals.length);
                    console.log(this.$vfm.dynamicModals[0]);
                },`


and CustomModal.vue:

```
<template>
  <vue-final-modal
      v-slot="{ close }"
      v-bind="$attrs"
      classes="modal-container"
      content-class="modal-content"
      v-on="$listeners"
  >
    <button class="modal__close" @click="close">
    </button>
    <span class="modal__title">Hello, vue-final-modal</span>
    <div class="modal__content">
      <p>Vue Final Modal is a renderless, stackable, detachable and lightweight modal component.</p>
    </div>
  </vue-final-modal>
</template>
<script>
export default {
  inheritAttrs: false

}
</script>
```

result:

![image](https://user-images.githubusercontent.com/57954182/199193786-ef2636ba-1015-421e-b37d-3eb393fbe337.png)

Nothing is showed up.

**Comment by flaczkiDomowe** [comment]
However, I tried different approach and I did 
```
import { $vfm, vfmPlugin, ModalsContainer } from 'vue-final-modal'

window.$vfm = $vfm;
...
app.component('CustomModal',require('./components/dialogs/CustomModal'));
app.component('modals-container',ModalsContainer);
``` 

and deleted `this `from code

```
 $vfm.show({ component: 'CustomModal' });
                    console.log($vfm.dynamicModals.length);
                    console.log($vfm.dynamicModals[0]);
```

The result is 
![image](https://user-images.githubusercontent.com/57954182/199194767-85f105f0-a5bd-4bbb-9eec-83c5f141fbf6.png)

**Comment by bradley-varol** [comment]
[I have reproduced this issue on CodeSandBox.](https://codesandbox.io/s/nuxt-2-vue-final-modal-6rbr21?file=/components/Modal.vue)

Looks like `Modal.vue` isn't even created when clicking.

**Comment by hunterliu1003** [comment]
Hi @bradley-varol 

Thank you for provide the reproduction.
I tried to remove the duplicate register of `ModalsContainer` in `layouts/default.vue`
```
<script>
import { ModalsContainer } from "vue-final-modal";

export default {
  components: {
    ModalsContainer,
  },
};
</script>
```

And this work
https://codesandbox.io/s/nuxt-2-vue-final-modal-forked-y0y2bh?file=/layouts/default.vue

So weird 🤔

**Comment by bradley-varol** [comment]
> https://codesandbox.io/s/nuxt-2-vue-final-modal-forked-y0y2bh?file=/layouts/default.vue

Nice! Looks like ModalsContainer was already registered globally?

**Comment by flaczkiDomowe** [comment]
Oki, my team decided that we don't switch for Vue 3 so I will not need that modal right now.
