### ISSUE TITLE
LIVE DEMO not working on document page

### ISSUE THREAD

**Issue by tuanhaviet22** [vue-final/vue-final-modal#269]
Hello team, 

I trying to decide use that lib or not but I faced an error when running your demo on page: https://vue-final-modal.org/examples/livedemo/

On the console, I see an error related to nuxt combined 

Can you check?! 

Thanks!

![image](https://user-images.githubusercontent.com/46513483/199641367-8a1c2c85-5eda-4af2-bc8a-3666a6ad37e9.png)

**Comment by hunterliu1003** [comment]
@tuanhaviet22 
Thanks a lot 
Just fixed it.

**Comment by GabrielaPavlova** [comment]
Hi team i have problem i use vue final modal but from yesterday i used to have an error
![Uploading IMG_20221103_114244.jpg…]()
