### ISSUE TITLE
@before-close should pass event as parameter to make it stoppable

### ISSUE THREAD

**Issue by ul8** [vue-final/vue-final-modal#27]
The @before-close should provide a mechanism to cancel the close action.

For example if form fields within the modal have changed, we want to be able to prompt the user if they want to move away or not, and if they deny, do not close the modal.

if the @before-close would pass the event, and we could run event.stop() on it would be perfect.

I guess the same applies to @before-open, though I personally do not have a use case for it yet.

**Comment by hunterliu1003** [comment]
Nice suggestion! I added this to roadmap first.
`vue-js-modal` stop event by calling `event.cancel()`.

**Comment by ul8** [comment]
Thanks! Yes, that was a typo, I meant event.stop()

**Comment by hunterliu1003** [comment]
Hi @ul8,

This enhancement is published at:

- `0.20.1` for Vue 2
- `1.7.1` for Vue 3
