### ISSUE TITLE
Problem with vue-final-modal

### ISSUE THREAD

**Issue by GabrielaPavlova** [vue-final/vue-final-modal#270]
Hi team I have a problem with vue-final-modal since yesterday

I use version 3.4.10/ Windows (But I have the same problem in any other version before 3.5)
When I load a Page I see this in console 

**Uncaught TypeError: t.withScopeId is not a function
    at vue-final-modal:7:16700
    at jsdelivr-header.js:7:1
    at jsdelivr-header.js:7:1**

**Unknown custom element: <vue-final-modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option**.

**Comment by hunterliu1003** [comment]
@GabrielaPavlova,
I think you're using the vue-final-modal by CDN.
I'm really sorry I delete the `next` tag yesterday.
I just add it back, please check it again if it's fixed

**Comment by GabrielaPavlova** [comment]
Yes I use https://cdn.jsdelivr.net/npm/vue-final-modal@3.4.10/dist/VueFinalModal.umd.min.js CDN for Vue version 2
I will check

**Comment by GabrielaPavlova** [comment]
No I have same problem

**Comment by GabrielaPavlova** [comment]
And I import it the component with this syntax
 components: {
      VueFinalModal: window.VueFinalModal.VueFinalModal,
    },

**Comment by hunterliu1003** [comment]
Or try using this CDN link

https://cdn.jsdelivr.net/npm/vue-final-modal@3

**Comment by GabrielaPavlova** [comment]
I use Vue - version 2. The Example and the CDN is with version 3

**Comment by hunterliu1003** [comment]
oh if you are using vue 2
please use the vue2 please use the vue-final-moda@2.x
https://codepen.io/hunterliu1003/pen/ZEWoYeE

**Comment by GabrielaPavlova** [comment]
Everything works prop with. There is no issues with it
https://cdn.jsdelivr.net/npm/vue-final-modal@2.4.3/dist/VueFinalModal.umd.min.js 

Thank you for you support and patient.

**Comment by hunterliu1003** [comment]
No problem👍
