### ISSUE TITLE
Typescipt TS2349: This (vfmPlugin) expression is not callable.

### ISSUE THREAD

**Issue by mshamaseen** [vue-final/vue-final-modal#278]
### Version

vue-final-modal: 3.4.10
vue: 3.2.38

### OS
Linux

## codesandbox
https://codesandbox.io/s/hello-vite-forked-nwcwk3?file=/src/main.ts

### Steps to reproduce
Just install Vite & Vue3 & TS, try to use vfmPlugin in global registration, a ts error will appear saying:

```Expected 0 arguments, but got 1```

then if I added `global.d.ts` in the project with the following:

```
// define the setup options
import { type VueFinalModalProperty} from "vue-final-modal";

declare module 'vue/types/vue' {
    interface Vue {
        $vfm: VueFinalModalProperty
    }
}
```

The error changed to:

`TS2349: This expression is not callable.   Type 'typeof import("node_modules/vue-final-modal/types/index")' has no call signatures.`

### What is Expected?
to work without any TS error XD

**Comment by hunterliu1003** [comment]
Fixed in v3.4.11

https://codesandbox.io/s/hello-vite-forked-8ny10c?file=/src/main.ts

```ts
import { createApp } from "vue";
import App from "./App.vue";
import "./index.css";
import { vfmPlugin } from "vue-final-modal";

const app = createApp(App);
app.use(
  vfmPlugin({
    key: "$vfm",
    componentName: "VueFinalModal",
    dynamicContainerName: "ModalsContainer"
  })
);

app.mount("#app");

```
