### ISSUE TITLE
VFM v4.0.0-rc.2 injection "Symbol(vfm)" not found / Cannot destructure property 'modals' of 'se(...)' as it is undefined.

### ISSUE THREAD

**Issue by lisunovdv** [vue-final/vue-final-modal#284]
### Version

vue-final-modal: v4.0.0-rc.2
vue: v3.2.41-v3.2.45

### OS

Mac

### Reproduction Link
https://playcode.io/1013585

### Steps to reproduce
See: https://playcode.io/1013585

### What is Expected?
VFM works correctly

### What is actually happening?

```shell
TypeError: Cannot destructure property 'modals' of 'se(...)' as it is undefined.
    at setup (<anonymous>:504:30)
    at callWithErrorHandling (<anonymous>:298:20)
    at setupStatefulComponent (<anonymous>:5888:27)
    at setupComponent (<anonymous>:5850:38)
    at mountComponent (<anonymous>:4603:9)
    at processComponent (<anonymous>:4581:11)
    at patch (<anonymous>:4299:13)
    at mountChildren (<anonymous>:4444:9)
    at mount (<anonymous>:5306:13)
```

```console
[Vue warn]: injection "Symbol(vfm)" not found.

 at <CoreModal
ref_key="CoreModalComp"
ref=Ref<
undefined
>
modalId=undefined
 ...
>

 at <VueFinalModal
class="flex justify-center items-center"
content-class="flex flex-col max-w-xl mx-4 p-4 bg-white dark:bg-gray-900 border dark:border-gray-700 rounded-lg space-y-2"
onUpdate:modelValue=fn
 ...
>

 at <ConfirmModal
modelValue=false
onUpdate:modelValue=fn
title="Hello World!"
 ...
>

 at <Preview>

 at <App>
[Vue warn]: Unhandled error during execution of setup function

 at <CoreModal
ref_key="CoreModalComp"
ref=Ref<
undefined
>
modalId=undefined
 ...
>

 at <VueFinalModal
class="flex justify-center items-center"
content-class="flex flex-col max-w-xl mx-4 p-4 bg-white dark:bg-gray-900 border dark:border-gray-700 rounded-lg space-y-2"
onUpdate:modelValue=fn
 ...
>

 at <ConfirmModal
modelValue=false
onUpdate:modelValue=fn
title="Hello World!"
 ...
>

 at <Preview>

 at <App>
```

**Comment by hunterliu1003** [comment]
Hey @lisunovdv ,

You have to create the vfm instance with `createVfm` and register it as a Vue plugin, and import the required css.
See new version of documentation: https://v4.vue-final-modal.org/get-started/guide/setup
```ts
import { createApp } from 'vue'
import App from './App.vue'

import { createVfm } from 'vue-final-modal'
import 'vue-final-modal/style.css'

const vfm = createVfm()
createApp(App).use(vfm).mount('#app')
```

**Comment by lisunovdv** [comment]
Ohhhhh, my bad! I'm so sorry! Thanks a lot!  🙇‍♂️
I very much appreciate your project!
Thank you!

**Comment by aless673** [comment]
similar error with stable release 4.0.0

```
[Vue warn]: injection "Symbol(vfm)" not found. 
  at <ModalsContainer> 
  at <MyComponent>
  ....
```

**Comment by hunterliu1003** [comment]
> similar error with stable release 4.0.0
> 
> ```
> [Vue warn]: injection "Symbol(vfm)" not found. 
>   at <ModalsContainer> 
>   at <MyComponent>
>   ....
> ```

@aless673

Do you register the plugin like this?

```ts
import { createApp } from https://github.com/vuejs/core
import App from './App.vue'

import { createVfm } from https://github.com/hunterliu1003/vue-final-modal
import https://github.com/hunterliu1003/vue-final-modal

const vfm = createVfm()
createApp(App).use(vfm).mount('#app')

```

**Comment by aless673** [comment]
> 

like this

```
import MyComponent from './MyComponent.vue'
import {createApp} from 'vue'
import { createVfm } from 'vue-final-modal'
import 'vue-final-modal/style.css'

const vfm = createVfm()

createApp({})
  .component('MyComponent', MyComponent)
  .use(vfm)
  .mount('#myComponent')
```

and my MyComponent.vue

```
<script setup lang="ts">
import { ModalsContainer } from 'vue-final-modal'
</script>
<template>
  <div>
    <ModalsContainer />
  </div>
</template>
```

**Comment by aless673** [comment]
> > similar error with stable release 4.0.0
> > ```
> > [Vue warn]: injection "Symbol(vfm)" not found. 
> >   at <ModalsContainer> 
> >   at <MyComponent>
> >   ....
> > ```
> 
> @aless673
> 
> Do you register the plugin like this?
> 
> ```ts
> import { createApp } from 'vue'
> import App from './App.vue'
> 
> import { createVfm } from 'vue-final-modal'
> import 'vue-final-modal/style.css'
> 
> const vfm = createVfm()
> createApp(App).use(vfm).mount('#app')
> ```

we should re-open the issue

**Comment by aless673** [comment]
@hunterliu1003 can you re-open the issue ?

**Comment by P0TER** [comment]
@hunterliu1003 @aless673 Here is the answer to why this happens: https://stackoverflow.com/a/68361722

**Comment by hunterliu1003** [comment]
Is this issue still exist in the latest version of vue-final-modal@4.4.4?

**Comment by P0TER** [comment]
> Is this issue still exist in the latest version of vue-final-modal@4.4.4?

@hunterliu1003 I returned fixes from my latest message and updated vue-final-modal. It works fine now. Thank you
