### ISSUE TITLE
Nuxt 3 module installation

### ISSUE THREAD

**Issue by noook** [vue-final/vue-final-modal#285]
### Is your feature request related to a problem? Please describe.

The module is compatible with both of Vue 2 and 3, and Nuxt. However, Nuxt 3 handles Typescript differently as the types are generated by the module, and injected in the `.nuxt` folder instead of the project's `tsconfig.json`

### Describe the solution you'd like

Install the module in the `modules` section of `nuxt.config.ts`

### Describe alternatives you've considered

Inserting types in tsconfig.json, but it's not recommended

**Comment by xrayian** [comment]
is this done?

**Comment by noook** [comment]
It looks like: https://vue-final-modal.org/get-started/guide/setup#nuxt-3
