### ISSUE TITLE
vue-final-modal breaks Vite build in monorepo

### ISSUE THREAD

**Issue by vonkanehoffen** [vue-final/vue-final-modal#286]
### Version

vue-final-modal: 3.4.11
vue: 3.2.45
nuxt: N/A

### OS

Mac

### Reproduction Link

https://github.com/vonkanehoffen/vue2-3-monorepo/tree/minimal-vue2

### Steps to reproduce

Start a codespace on the `minimal-vue2` branch above, then:
```
pnpm i
cd vue-3-project
pnpm dev
```

### What is Expected?

The project should build and show a modal.

### What is actually happening?

Multiple build errors, referencing Vue 2, despite the package dependency being Vue 3. The only reference to Vue 2 in the entire workspace is in a different package (vue-2-minimal) :
```
(node:5486) UnhandledPromiseRejectionWarning: Error: Build failed with 20 errors:
../node_modules/.pnpm/vue-final-modal@3.4.11/node_modules/vue-final-modal/dist/VueFinalModal.esm.js:1:79: ERROR: No matching export in "../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.runtime.esm.js" for import "withScopeId"
../node_modules/.pnpm/vue-final-modal@3.4.11/node_modules/vue-final-modal/dist/VueFinalModal.esm.js:1:92: ERROR: No matching export in "../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.runtime.esm.js" for import "pushScopeId"
../node_modules/.pnpm/vue-final-modal@3.4.11/node_modules/vue-final-modal/dist/VueFinalModal.esm.js:1:105: ERROR: No matching export in "../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.runtime.esm.js" for import "popScopeId"
../node_modules/.pnpm/vue-final-modal@3.4.11/node_modules/vue-final-modal/dist/VueFinalModal.esm.js:1:117: ERROR: No matching export in "../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.runtime.esm.js" for import "withDirectives"
../node_modules/.pnpm/vue-final-modal@3.4.11/node_modules/vue-final-modal/dist/VueFinalModal.esm.js:1:133: ERROR: No matching export in "../node_modules/.pnpm/vue@2.7.14/node_modules/vue/dist/vue.runtime.esm.js" for import "openBlock"
...
    at failureErrorWithLog (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:1574:15)
    at /workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:1032:28
    at runOnEndCallbacks (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:1446:61)
    at buildResponseToResult (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:1030:7)
    at /workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:1142:14
    at responseCallbacks.<computed> (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:679:9)
    at handleIncomingPacket (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:734:9)
    at Socket.readFromStdout (/workspaces/vue2-3-monorepo/node_modules/.pnpm/esbuild@0.15.16/node_modules/esbuild/lib/main.js:655:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
```

Really confused as to what's causing this, but all I can think is it's something to do with the build of `vue-final-modal`. See the other branch in that repo that pulls in `vue3-apexcharts` instead without issue. I've also tried this with `npm` to rule out the package manager itself with the same result. The host `vue-3-project` is just a vanilla `npm init vue@latest`.

Any ideas anyone? I'm stumped! 🤯 😄

**Comment by hifizz** [comment]
It seems like there's a version conflict issue. I noticed that you are using Vue 3, but the version of `vue-final-modal` is targeting Vue 2. This could be the reason for the build errors you're encountering.

To fix this issue, you'll need to update `vue-final-modal` to the latest version compatible with Vue 3.x. The current latest version is `4.4.4`.

Try updating the `dependencies` in the `vue-3-project/package.json` file:

```json
"dependencies": {
  "vue": "^3.2.45",
  "vue-final-modal": "^4.4.4"
}
```

Then run `pnpm i` and `pnpm dev`. This will install and use the `vue-final-modal` version compatible with Vue 3.x, which should solve the problem you're experiencing. Hope this helps!

**Comment by hifizz** [comment]
> @vonkanehoffen 

It seems like there's a version conflict issue. I noticed that you are using Vue 3, but the version of `vue-final-modal` is targeting Vue 2. This could be the reason for the build errors you're encountering.

To fix this issue, you'll need to update `vue-final-modal` to the latest version compatible with Vue 3.x. The current latest version is `4.4.4`.

Try updating the `dependencies` in the `vue-3-project/package.json` file:

```json
"dependencies": {
  "vue": "^3.2.45",
  "vue-final-modal": "^4.4.4"
}
```

Then run `pnpm i` and `pnpm dev`. This will install and use the `vue-final-modal` version compatible with Vue 3.x, which should solve the problem you're experiencing. Hope this helps!
