### ISSUE TITLE
Make reserveScrollBarGap optional when lockScroll is enabled

### ISSUE THREAD

**Issue by trippyfish** [vue-final/vue-final-modal#288]
### Is your feature request related to a problem? Please describe.
Make reserveScrollBarGap optional when lockScroll is enabled

### Describe the solution you'd like
Add a reserveScrollBarGap boolean to VueFinalModal props, have it dynamically set the boolean when enabling bodyScrollLock.

### Additional context
I have `overflow-y-scroll` set on my html element which shows the scrollbar permanently. Therefore I don't need the additional padding.

**Comment by negezor** [comment]
Faced with the same problem, I use the `scrollbar-gutter: stable` property. The `reserveScrollBarGap` property should be optional.

**Comment by hunterliu1003** [comment]
Fixed in [v4.4.4](https://www.npmjs.com/package/vue-final-modal/v/4.4.4)
