### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by neko2h** [vue-final/vue-final-modal#294]
### Is your feature request related to a problem? Please describe.
Hi mate, thank you for this really usefull library. So the main problem is documentation. I installed it with yarn just like you wrote in docs. And by default it installed the third version. I've tried to use it with Nuxt 3 and i obviously failed. And later on i found out that there is a fourth version. I didnt even know that it exists, because the git readme didnt say anything about it, just like the main site.

### Describe the solution you'd like
So what i propose is to mention about it in readme, add link to v4 subdomain, and write how to add specific version of this library to the project.

**Comment by mesqueeb** [comment]
improved docs and official release of VFM 4.0.0 planned soon! At latest sometime in Januari!

**Comment by Mini-ghost** [comment]
@mesqueeb @hunterliu1003 

I thought maybe something about v4 should be mentioned in the README of the main branch ?

**Comment by mesqueeb** [comment]
@Mini-ghost documentation PRs welcome! 🎉

Please note that V4 syntax might still change a bit.
