### ISSUE TITLE
Why when I open modal, padding-right: 17px gets added to the body

### ISSUE THREAD

**Issue by kenyonbwrs** [vue-final/vue-final-modal#296]
### Version

vue-final-modal: 3.4.11
vue: 3
nuxt: not using

### OS
Windows

### Reproduction Link
None

### Steps to reproduce
I really don't know. It is just pushing everything around.

### What is Expected?
There to not be a `padding-right; 17px;` on the body as it is messing with my already existing styles.

**Comment by hunterliu1003** [comment]
Hey @kenyonbwrs 
The 17px padding comes from the `lock-scroll`, so please try to set `:lock-scroll="false"`

**Comment by kenyonbwrs** [comment]
Alright. Thanks!
