### ISSUE TITLE
[v4] Accessing `$vfm` on template throws type error when use TypeScript

### ISSUE THREAD

**Issue by Mini-ghost** [vue-final/vue-final-modal#302]
### Version

vue-final-modal: v4.0.0-rc.6
vue: v3.2.45"

### OS

Mac

### What Happen

![截圖 2023-01-10 下午4 15 09](https://user-images.githubusercontent.com/39984251/211497037-cf3e5321-3c85-40c8-9ac7-fb3c6499c84d.png)

### What is Expected?

It should add type that `Vfm` to Vue's `ComponentCustomProperties`.

**Comment by hunterliu1003** [comment]
Fixed in  [v4.0.0-rc.7](https://www.npmjs.com/package/vue-final-modal/v/4.0.0-rc.7)
