### ISSUE TITLE
How to use params in modal script

### ISSUE THREAD

**Issue by odion-cloud** [vue-final/vue-final-modal#309]
i want to use modal params not only in  template but also in script tag of modal How do I use it

**Comment by hunterliu1003** [comment]
@odion-cloud 

Sorry I think `params` is not a good practice for managing a modal, so it was removed in vue-final-modal@4.x.
And currently I recommend to upgrade to vue-final-modal@4.x and use `useModal()` to manage dynamic modals.
Please checkout the [migration guide](https://vue-final-modal.org/get-started/guide/migration-guide) and [useModal()](https://vue-final-modal.org/api/composables/use-modal)
