### ISSUE TITLE
v-deep deprecated in vue 3.0.3

### ISSUE THREAD

**Issue by manuelmazzuola** [vue-final/vue-final-modal#31]
### Version

vue-final-modal: 1.7.1
vue: 3.0.3
@vue/compiler-sfc: 3.0.3

### What is actually happening?

`::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.`

**Comment by hunterliu1003** [comment]
Hi @manuelmazzuola,

Thanks for your feedback. I found the [RFC#0023](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md).

I will fix the issue and publish a new version.

**Comment by hunterliu1003** [comment]
The issue was fixed in:

- v1.8.1 for Vue 3
