### ISSUE TITLE
v4 improvement: scoped styles

### ISSUE THREAD

**Issue by R1ze13** [vue-final/vue-final-modal#312]
### Is your feature request related to a problem? Please describe.
Hi, first of all I want to say thanks for the good library. I tried to upgrade to version 4 in an existing project and encountered an inconvenience:
In version 4, I can't style the component with scoped styles because the VueFinalModal component uses regular styles and there are no data attributes for scoped styles in the markup. In a project that mostly uses just scoped styles, this becomes a big inconvenience, because some of the styles just don't work and it's not immediately clear why and even more, how to fix it.

A simple example: I have some basic modal window. I want to add a new modal window, which must have a non-standard width. To do this, I add a separate css class and encounter a situation when the rule for this class doesn't work

### Describe the solution you'd like
I propose to make VueFinalModal and other components always use scoped styles by default. This would help people like me who always try to use scoped styles, but at the same time it wouldn't hurt people who use regular styling, because they could use special selectors https://vuejs.org/api/sfc-css-features.html#scoped-css

### Describe alternatives you've considered
Use a mix of scoped styles and regular styles. Unfortunately, this is a huge discomfort due to the fact that every developer now needs to understand when and what styles to use. This is an additional cognitive load, which I would like to avoid

### Additional context
Screenshot of the markup. Perhaps this will help you understand the situation I'm talking about
https://snipboard.io/gFHXP7.jpg

**Comment by JackEdwardLyons** [comment]
I agree, this would be super helpful

**Comment by hunterliu1003** [comment]
Thanks for your feedback!

I tried to use scoped styles in VueFinalModal, but it doesn't solve the issue (See bd2712e).
I found this issue from vue 3: https://github.com/vuejs/core/issues/2669#issuecomment-734434188, and you can see [this CodeSandBox](https://codesandbox.io/s/laughing-gagarin-4mlln?file=/src/components/CompB.vue)
It seems an issue from the Teleport, and VueFInalModal is based on the Teleport component.
So I think currently we have no way to improve this.

**Comment by hunterliu1003** [comment]
This issue is closed because I still can't find any solution to improve it.
