### ISSUE TITLE
How do I close a modal?

### ISSUE THREAD

**Issue by roelVerdonschot** [vue-final/vue-final-modal#321]
Using de useModal() function in setup() is there a way to close the modal from inside the component manually? i tried to use $emit('close') and $emit('confirm') but this did not do anything.

`setup(props) {
        return {
            category_modal: useModal({
                component: CategoryModal
            })
        }
    },`

### Version
"vue-final-modal": "^4.0.0"
 "vue": "^3.2.0",

### OS
Mac

**Comment by hunterliu1003** [comment]
@roelVerdonschot 

You can try to emit a event call `onCloseModal`, then use `category_modal .close()` to close the modal.

```ts
const category_modal = useModal({
  component: CategoryModal,
  attrs: {
    // onCloseModal should be a event, emit by `CategoryModal`
    onCloseModal: () => category_modal.close()
  }
})

category_modal.open()
```

Please checkout the format of the useModal options for more detail: https://vue-final-modal.org/api/composables/use-modal#passing-props-and-events
