### ISSUE TITLE
When the DRAG is turned on, How to set initial width and height position

### ISSUE THREAD

**Issue by ishaiavrahami** [vue-final/vue-final-modal#327]
When drag is turned on the modal doesn't add style to content only after first drag. Any reason i'm experiencing this?

### Version

vue-final-modal: 3.4.4
vue: 3

### OS

Mac 

### Steps to reproduce
Set `:min-width` and look at the content style which should include `min-width`

**Comment by hunterliu1003** [comment]
@ishaiavrahami 

You can just override the initial style of .vfm__content to achieve this. For example:

.vfm__content {
  top: 10px;
  left: 10px;
  width: 300px;
  height: 200px;
}
