### ISSUE TITLE
Can't find variable: TouchEvent in Safari

### ISSUE THREAD

**Issue by synointaivaras** [vue-final/vue-final-modal#329]
### Version

vue-final-modal: v4.0.3
vue: v3.2.45
tinymce: v4.0.7

### OS

Mac Ventura 13.1

### Steps to reproduce
We open tinymce in vue-final-modal and clicking on e.g. source code or link button it is opening another modal box and then in Safari console log we are getting this issue:

ReferenceError: Can't find variable: TouchEvent index.es.js:469

As I understand this is related to Safari as Chrome does not fire this issue.

**Comment by hunterliu1003** [comment]
The bug was fixed in [v4.0.4](https://github.com/vue-final/vue-final-modal/releases/tag/v4.0.4)

**Comment by synointaivaras** [comment]
Thank you! Super fast, already tried and it works!
