### ISSUE TITLE
[Bug] Can't focus input when there are nested modals.

### ISSUE THREAD

**Issue by hunterliu1003** [vue-final/vue-final-modal#332]
Can't focus input when there are nested modals.
If there are nested modals, VFM should disable previous `focusTrap` of modals

**Comment by stonega** [comment]
Is this bug fixed already? I have the same issue. Do you have any solutions?

**Comment by hunterliu1003** [comment]
@stonega 
Yes, the bug is fixed already. 🤔

**Comment by stonega** [comment]
@hunterliu1003 Thanks for your reply. I made a mistake, it was a issue related to nested slot but not nested modals, input is not focused inside nested slot, maybe I should open a new issue about it ? 
You can close this.
