### ISSUE TITLE
Import createVfm in main.ts throw error and browser too

### ISSUE THREAD

**Issue by KevinBazimo** [vue-final/vue-final-modal#336]
### Version

vue-final-modal: 4.0.6
vue: 3.2.42 => composition API
vite: 3.2.3

### Steps to reproduce
Add VFM to main.ts, typescript throw error:
[
![image](https://user-images.githubusercontent.com/101792702/221830002-95273adf-f8c1-43a3-be7b-5c423a6c3034.png)
](url)

Then when a add ModalsContainer to app.vue, my browser thorw error:
[
![image](https://user-images.githubusercontent.com/101792702/221830264-dd13c726-6e39-4317-bfb7-828f1a51a6b5.png)
](url)

[
![image](https://user-images.githubusercontent.com/101792702/221830391-c60399e1-2262-4848-949b-c97d592800fd.png)
](url)

**Comment by Sergdan1992** [comment]
I have same issue.  If check vfm instance, got `undefined`
```javascript
import { useVfm } from 'vue-final-modal'
const vfm = useVfm() // undefined
```
Only created instance exist
```javascript
const vfm = createVfm() // vfm-instance
```
Maybe some trouble with [vfmSymbol](https://github.com/vue-final/vue-final-modal/blob/master/packages/vue-final-modal/src/injectionSymbols.ts#LL4C15-L4C15)

FYI: My project based on  vue-cli

**Comment by hunterliu1003** [comment]
There are two examples made with stackblitz and they works properly:
Vue 3: https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/vue3
Nuxt 3: https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3
Please checkout if you register vue-final-modal correctly base on these two examples.
If it's still not working, please provide a reproduction like stackblitz or codesandbox.

**Comment by SDKexplorer** [comment]
I have the same problem. I've deleted the yarn.lock file in my case and I got rid of dynamicModals component
