### ISSUE TITLE
Add slots to `useModalSlot`

### ISSUE THREAD

**Issue by matthew-dean** [vue-final/vue-final-modal#348]
### Is your feature request related to a problem? Please describe.
I want to be able to use a SFC for a modal slot. This content also has slots. However, `useModalSlots` throws a type error when trying to define content for slots.

### Describe the solution you'd like
I want to slot in content from the parent wrapper into the slot wrapper, like:
```ts
const slots = useSlots()

useModal({
  component: VueFinalModal,
  defaultModelValue: props.modelValue,
  attrs: {
  // ...
  },
  slots: {
    default: useModalSlot({
      component: DialogContent,
      attrs: {
        title: props.title
      },
      slots: {
        default: slots.default
      }
    })
  }
})
```

### Describe alternatives you've considered
I guess the alternative is just using a string template, which I'm trying to avoid.

**Comment by hunterliu1003** [comment]
@matthew-dean 
Currently, `useModal()` only allowed to pass slots with one layer, this is designed in purpose because it's hard to manage nested slots. I don't have a good idea of how to implement the feature yet.

**Comment by hunterliu1003** [comment]
@Mini-ghost Do you have any idea to achieve this?
