### ISSUE TITLE
onOpened, onClosed hooks are not triggered

### ISSUE THREAD

**Issue by SDKexplorer** [vue-final/vue-final-modal#349]
### Reproduction Link
https://stackblitz.com/edit/github-wtv4qd?file=src/components/MyModalPreview.vue

### Steps to reproduce
call modal.open() or mocal.close()

### What is Expected?
To trigger handlers

### What is actually happening?
Nothing

**Comment by hunterliu1003** [comment]
@SDKexplorer 
You have to define the event and emit them by yourself in MyModal:
https://stackblitz.com/edit/github-wtv4qd-s55evb?file=src%2Fcomponents%2FMyModal.vue
