### ISSUE TITLE
Styles not available when pushed to production

### ISSUE THREAD

**Issue by AlbatiQue** [vue-final/vue-final-modal#35]
Hey,

Great plugin and seems to work well. I currently facing a weird problem that when I test locally everything works as expected.
When I push my code to production environment all the classes for 

`.vfm--inset, 
.vfm--fixed, vfm__overlay vfm--overlay vfm--absolute vfm--inset
`
are not available. Am i doing something wrong? I'm using the nuxt.

I have this in my Build configuration 
` build: {
    /*
     ** You can extend webpack config here
     */
    transpile: ['vue-final-modal']
  },`

looking forward to your reply!

**Comment by hunterliu1003** [comment]
Hi @AlbatiQue,

Could you please provide the reproduction about the issue?

**Comment by AlbatiQue** [comment]
Hey, 

Hunter I just did everything like in the vue-final modal documentation. I did not any extra classes for .vfm--inset, .vfm--fixed etc. But I did add extra classes for styling the modal itself. And these are loaded.
Just not the vfm classes.

**Comment by hunterliu1003** [comment]
Which version are you using?
If you share your repository, so that I can debug for the issue

**Comment by bebetoalves** [comment]
If you are using purgecss, and you have styled the modal using ::v-deep(.class-name) etc, you need to put "v-deep" in the purgecss [safelist](https://purgecss.com/safelisting.html).

**Comment by AlbatiQue** [comment]
@bebetoalves 
Thanks for your reply, Do i need to add every single class? 
Like this
` purge: {
    content: [
      './components/**/*.{vue,js}',
      './layouts/**/*.vue',
      './pages/**/*.vue',
      './plugins/**/*.{js,ts}',
      './nuxt.config.{js,ts}'],
    options: {
      safelist: ['::v-deep .modal-container', '::v-deep .modal-content']
    }
  }`

**Comment by bebetoalves** [comment]
No, just /v-deep/.

Example: safelist: [/v-deep/]

**Comment by hunterliu1003** [comment]
This problem seems to be solved.
