### ISSUE TITLE
LockScroll control before/after animation ?

### ISSUE THREAD

**Issue by lyneal** [vue-final/vue-final-modal#350]
### Version

vue-final-modal: v4.0.11
nuxt: v3.3.1

### OS

Windows

### What is actually happening?

Hello,

Currently, the scroll is locked only once the modal appears. Is it possible to reverse and lock before the modal appears?

**Comment by hunterliu1003** [comment]
@lyneal I think the issue is related to #352.
The default behavior was changed to lock body scroll right after the modal transition start in [v4.1.4](https://npmjs.com/package/vue-final-modal/v/4.1.4).
Please let me know if the new version solve your problem.

**Comment by lyneal** [comment]
> @lynealJe pense que le problème est lié à #352 . Le comportement par défaut a été modifié pour verrouiller le défilement du corps juste après le début de la transition modale dans la [v4.1.4](https://npmjs.com/package/vue-final-modal/v/4.1.4) . S'il vous plaît laissez-moi savoir si la nouvelle version résout votre problème.

Indeed the problem seems to be solved! Thank you very much for the correction.
