### ISSUE TITLE
Modal content "jumps" (flicker) from left to right on open

### ISSUE THREAD

**Issue by xaja** [vue-final/vue-final-modal#352]
### Version

vue-final-modal: 4.1.1
vue: 3.2.45
nuxt: nope

### OS

Windows (Chrome)

### Reproduction Link
Any demo in Official Docs

### What is actually happening?
there is a time lag between the assignment of the body overflow style (and padding-right) and the showing of the modal content. 

even if you turn off the animation, then this jump will be visible for a split second, very annoying

Before i used vfm3 — everything will be ok with this

**Comment by hunterliu1003** [comment]
@xaja Thanks for your feedback
I'll fix it and publish a patch version in weekend

**Comment by hunterliu1003** [comment]
@xaja The issue was fixed in version [v4.1.3](https://www.npmjs.com/package/vue-final-modal/v/4.1.3)
