### ISSUE TITLE
How to passing props to global modal ?

### ISSUE THREAD

**Issue by evdevru** [vue-final/vue-final-modal#353]
### Version

vue-final-modal: 4.0.11
vue: 3.2

How to passing props to global modal ? In v3 you have event onBeforeOpen with props. How to passing in v4 ? Like open('NAME', props)

**Comment by hunterliu1003** [comment]
You can use `useModal` to pass `props`, `events`, `slots`
You checkout this part of documentation:
https://vue-final-modal.org/api/composables/use-modal#passing-props-and-events

**Comment by evdevru** [comment]
> You can use `useModal` to pass `props`, `events`, `slots` You checkout this part of documentation: https://vue-final-modal.org/api/composables/use-modal#passing-props-and-events

That method require to use any event emitter if you using global modal to define global modals as authorization ? To access globally

**Comment by hunterliu1003** [comment]
I don't understand your question
