### ISSUE TITLE
Import cost of VFM greater than 60kb (gzip)

### ISSUE THREAD

**Issue by suhan0694** [vue-final/vue-final-modal#356]
### Version
vue-final-modal: 4.1.4
vue: "3.2.47"

Import cost of ```createVfm``` is currently resolving to **~177kb** and gzipped to **~64kb**.

![Vue-final-modal-size](https://user-images.githubusercontent.com/54325915/229569388-db44d48f-77d3-4c40-bfe9-a5c497cbc47b.JPG)

Is this the expected size? Am I missing anything here?

**Comment by hunterliu1003** [comment]
@suhan0694 I'm not sure how does the vscode extension calculate the bundle size of vue-final-modal

I think this is more accurate.
The building process show the bundle size of vue-final-modal, it's 0.41kb for style, 9.35kb for ESM and 7.43kb for UMD, 

<img width="778" alt="截圖 2023-04-04 上午10 18 54" src="https://user-images.githubusercontent.com/15190246/229669926-6935a345-72c5-4b7f-a3ef-bd729ccf7b17.png">

I also check the bundle size in [bundlephobia](https://bundlephobia.com/package/vue-final-modal@4.1.4), the `self` part of vue-final-modal only take 4.72kb.
<img width="1423" alt="截圖 2023-04-04 上午10 15 26" src="https://user-images.githubusercontent.com/15190246/229669561-dc0f83a8-3536-4df0-a1f7-9fdc10d23ce4.png">

**Comment by suhan0694** [comment]
Thank you @hunterliu1003. This provides a better picture.

FYI the extension on VSCode we are using is **Import Cost**
