### ISSUE TITLE
Show api doesn't work in vue 3

### ISSUE THREAD

**Issue by manuelmazzuola** [vue-final/vue-final-modal#36]
### Version
vue-final-modal: 1.8.0
vue: 3.0.4

### Reproduction Link
using api `show` doesn't work -> https://jsfiddle.net/05ougr6L/24/

### What is Expected?
Should open the modal

### What is actually happening?
Modal isn't showing

**Comment by hunterliu1003** [comment]
Hi @manuelmazzuola,

every modal component must have own `v-model`.

Here is the example https://jsfiddle.net/9uLx4r7s/

**Comment by manuelmazzuola** [comment]
should be specified in the documentation

thanks!

**Comment by hunterliu1003** [comment]
I agree, I will update the docs. 

Thanks for your feedback!

**Comment by hunterliu1003** [comment]
The documentation was updated
