### ISSUE TITLE
Sweetalert select not working in Firefox because of focusTrap

### ISSUE THREAD

**Issue by arwinvdv** [vue-final/vue-final-modal#360]
### Version

vue-final-modal: 
vue: 

### OS
Mac with Firefox

### Reproduction Link
https://stackblitz.com/edit/github-5vcwph

### Steps to reproduce

1. Open a modal (vue-final-modal)
2. Click on a button in the modal to open the sweetalert message
3. The select inside the swal message is not working in Firefox
https://github.com/sweetalert2/sweetalert2/issues/2617

### What is Expected?
That you can open the select dropdown inside the swal message regardless of the focusTrap.

### What is actually happening?
Select dropdown is not opening because of focusTrap, if we disable the focusTrap it is working fine.

**Comment by hunterliu1003** [comment]
@arwinvdv I have no idea how to fix this. Currently, the only way is to set `focusTrap` to `false`
