### ISSUE TITLE
How am I supposed to prevent a modal from being closed?

### ISSUE THREAD

**Issue by Twanghofer** [vue-final/vue-final-modal#367]
Since the Migration from v3 to v4, I am not sure how to do this. The [migration guide](https://vue-final-modal.org/get-started/guide/migration-guide) suggests, that 'It's easy to have a condition before open or before close the modal', but this won't work when using escToClose or clickToClose. 

How can I prevent a Modal from being closed with escToClose or clickToClose?

**Comment by jcmillett** [comment]
I'm also running into this issue. I want to allow click outside or escape key to close the dialog, but I want to run some logic first to verify it's what the user wants to do. Is this not possible?

**Comment by Twanghofer** [comment]
> I'm also running into this issue. I want to allow click outside or escape key to close the dialog, but I want to run some logic first to verify it's what the user wants to do. Is this not possible?

For the project in question I just stayed with v3, cause I didn't find a good solution yet

**Comment by hunterliu1003** [comment]
@Twanghofer 
Indeed.
When I rewrote v4, I did not consider this because I did not encounter this requirement in my experience. However, I agree with the situation you mentioned about escToClose and clickToClose. I will try to add the `event.stop()` function to v4, but I can't give you a guaranteed time yet.

**Comment by hunterliu1003** [comment]
The v4.5.0 is released
Now you can use `@beforeOpen="(event) => event.stop()"` or `@beforeClose="(event) => event.stop()"` to prevent the open or close modal.
Checkout: https://vue-final-modal.org/api/components/vue-final-modal#events
