### ISSUE TITLE
Cannot focus nested input

### ISSUE THREAD

**Issue by AmitJoki** [vue-final/vue-final-modal#369]
### Version

vue-final-modal: 4.0.11
vue: 3

### OS

Mac

### Reproduction Link

https://codesandbox.io/s/happy-tdd-tluovu?file=/src/ModalConfirm.vue

### Steps to reproduce

1. There's `Click me` button in the page -> Click it and click on input -> Works correctly. This is normal and expected.
2. Then there's a `Open modal` button which opens a Vue Final Modal which contains the same dropdown. Click on `Open modal` and repeat step 1, it does not work anymore. The input does not get focus.

### What is Expected?

Input should be focused.

### What is actually happening?

Input is not focused.

### Additional Info

Maybe related to: #332 ?

I have also disabled focusTrap by setting `:focusTrap="false"` but that does not make any difference.

**Comment by AmitJoki** [comment]
Seems like a case of HMR not working. It worked after a couple of refreshes.

**Comment by hgiesel** [comment]
Anybody discovering this afterwards: Focus the input in the `opened` event.
