### ISSUE TITLE
v-model change doesn't work in vue 3

### ISSUE THREAD

**Issue by manuelmazzuola** [vue-final/vue-final-modal#37]
### Version
vue-final-modal: 1.8.0
vue: 3.0.4

### Reproduction Link
doesn't work -> https://jsfiddle.net/05ougr6L/25/
this works -> https://jsfiddle.net/vc3sahx8/1/

### What is Expected?
Should open the modal

### What is actually happening?
Modal isn't showing

**Comment by hunterliu1003** [comment]
Hi @manuelmazzuola,

You should use `ref` to create a variable for `v-model`.

Here is the example https://jsfiddle.net/9uLx4r7s/

**Comment by manuelmazzuola** [comment]
thanks :up:
