### ISSUE TITLE
Error: [Vue Final Modal]: getActiveVfm was called with no active Vfm. Did you forget to install vfm?

### ISSUE THREAD

**Issue by mishabachkur** [vue-final/vue-final-modal#371]
I'm getting an error, but not consistently. I have included it in nuxt.config.ts

`modules: [
    '@vue-final-modal/nuxt'
  ],`

### Version

vue-final-modal: 4.4.2
@vue-final-modal/nuxt: 1.0.0
nuxt: 3.5.2

![image](https://github.com/vue-final/vue-final-modal/assets/3975266/6515cc60-820b-4848-9119-da95b540c332)
![image](https://github.com/vue-final/vue-final-modal/assets/3975266/82e64cd1-24f7-4239-b60f-ce23d1a68065)
![image](https://github.com/vue-final/vue-final-modal/assets/3975266/f5de12e5-d0f5-4efe-8298-e3fe0e0213db)

**Comment by mishabachkur** [comment]
@hunterliu1003 Can you help me?

**Comment by mishabachkur** [comment]
@hunterliu1003 I noticed a pattern that if you do a **nuxi build** and then **nuxi dev**, the bug disappears. If you do a **nuxi cleanup** and then **nuxi dev**, the bug reappears

**Comment by educbraga** [comment]
same here

**Comment by petrprikryl** [comment]
Fixed for me in latest 4.4.6 release :tada:

**Comment by hunterliu1003** [comment]
Please try to upgrade both `@vue-final-modal/nuxt` and `vue-final-modal`, then see if the error is fixed

```
"dependencies": {
    "@vue-final-modal/nuxt": "^1.0.2",
    "vue-final-modal": "^4.4.6"
  }
```
The latest nuxt 3 example:
https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3?file=package.json

**Comment by mishabachkur** [comment]
@hunterliu1003 I have updated 2 packages to the versions you mentioned. After running 'yarn dev,' I encountered the same error. When adding a [plugin](https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3?file=plugins%2Fvfm.ts), there is a warning: 'App already provides property with key "Symbol(vfm)." It will be overwritten with the new value.' However, if I immediately remove this [plugin](https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3?file=plugins%2Fvfm.ts) and run 'yarn dev' again, everything is fine.

**Comment by joao-pedro-alves** [comment]
Got the same issue but using Inertia in SSR mode...

**Comment by hunterliu1003** [comment]
Please try to use `@vue-final-modal/nuxt 1.0.3` and `vue-final-modal 4.5.0` see if it's fixed.
Here is the latest live demo of [Nuxt 3 Stackblitz Example](https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3?file=package.json)

**Comment by ozgencDev** [comment]
all packages lastest but error still occurs

**Comment by AndreiManya** [comment]
> all packages latest but error still occurs

same on ios 14 and lower
