### ISSUE TITLE
Pass real props instead of ComponentPublicInstance['$props']

### ISSUE THREAD

**Issue by Dodje** [vue-final/vue-final-modal#374]
### Is your feature request related to a problem? Please describe.
Increasing type safety. For now my IDE says that the type of `export type ComponentProps = ComponentPublicInstance['$props'];` is just empty object `{}`

### Describe the solution you'd like
Just export real props interface https://github.com/vuejs/core/pull/8083

### Additional context
Due to new features of vue3.3 we now able to reuse component interfaces for more convenient usage of wrapperings components

**Comment by hunterliu1003** [comment]
The props has type safety in vue-final-modal 4
