### ISSUE TITLE
Parent modal can be closed using ESC key after a nested modal is opened

### ISSUE THREAD

**Issue by Me-Phew** [vue-final/vue-final-modal#375]
### Version

vue-final-modal: 4.4.2
vue: 3.2.47
nuxt: 3.3.2

### OS

Windows

### Reproduction Link
[The problem can be seen in this example from the docs](https://vue-final-modal.org/use-cases/modal-nested)

### Steps to reproduce
Hit escape quickly during the opening of a nested modal or soon after it opens

### What is Expected?
The nested modal should stop opening or close and the parent modal should remain open

### What is actually happening?
The parent modal is closing leaving the nested modal open by itself

**Comment by hunterliu1003** [comment]
@Me-Phew Nice catch!

**Comment by hunterliu1003** [comment]
@Me-Phew It was fixed in [v4.4.3](https://github.com/vue-final/vue-final-modal/releases/tag/v4.4.3)

**Comment by Me-Phew** [comment]
@hunterliu1003 Great, thanks!
