### ISSUE TITLE
Module '"vue-final-modal"' has no exported member 'ModalsContainer'.ts(2305)

### ISSUE THREAD

**Issue by georginklv** [vue-final/vue-final-modal#383]
### Version

 "vue-final-modal": "^3.4.11"
"vue": "^3.3.4",
with composition API, TS, vite

### OS
 Windows

After build command I got an error TS2305: Module '"vue-final-modal"' has no exported member 'ModalsContainer'.
![image](https://github.com/vue-final/vue-final-modal/assets/44772981/92cf920b-b9b1-4f77-975c-9942fbcec9ee)
![image](https://github.com/vue-final/vue-final-modal/assets/44772981/4ee047b4-aec9-4c4f-88e3-b998ec502a8d)

**Comment by georginklv** [comment]
I upgrade the version to "vue-final-modal": "^4.4.5",

**Comment by hunterliu1003** [comment]
I am sorry that v3 is no longer maintain. If that's possible, please upgrade to v4 that fully rewrite with Typescript and having better DX. You can follow the [migration guide](https://v4.vue-final-modal.org/get-started/guide/migration-guide)
