### ISSUE TITLE
VueFinalModal is killing parent component?

### ISSUE THREAD

**Issue by Kocarik** [vue-final/vue-final-modal#386]
Hello,

I'm using latest version of vue fonal modal with vue 3 . And I would like know how VueFinalModal is workint as component. I'm using directly in my component VueFinalModal directive. But when I open modal I can not acces to any functon in my component, Looks like VueFinalModal is working as separate compoennt like parent<-> child compoenent?

**Comment by hunterliu1003** [comment]
I don't understand you question. Please provide more context and details, giving a live demo will be the fastest way to get my respond

**Comment by mikoca** [comment]
You can close this, thanks.
