### ISSUE TITLE
TypeError se(vue-final-modal/dist/index.es)

### ISSUE THREAD

**Issue by azabroflovski** [vue-final/vue-final-modal#389]
### TypeError
`undefined is not an object (evaluating 'e.touches.length')`

### Version

vue-final-modal: v4.4.2
vue: v3.3.4
nuxt: v3.7.3

### OS

macOS Sonoma 14.0 (MacBook Pro 13 M2)

### Reproduction Link

None (Error handled by Sentry)

### What is actually happening?

![telegram-cloud-document-2-5251203019554436024](https://github.com/vue-final/vue-final-modal/assets/33807338/67fa0962-00fe-462b-a313-084ca82d262e)

**Comment by hunterliu1003** [comment]
@azabroflovski 
You can check the [Stackblitz Nuxt 3 example](https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3?file=package.json) to see how to setup vfm with `@vue-final-modal/nuxt`

**Comment by hunterliu1003** [comment]
@azabroflovski I found the previous Stackblitz Nuxt 3 example is wrong one. so please check this for using `@vue-final-modal/nuxt`: [Stackblitz Nuxt 3 example](https://stackblitz.com/github/vue-final/vue-final-modal/tree/master/examples/nuxt3)
It's using `vue-final-modal` 4.5.0 and `@vue-final-modal/nuxt` 1.0.3
