### ISSUE TITLE
live demo not work

### ISSUE THREAD

**Issue by jprando** [vue-final/vue-final-modal#40]
Hi!

in "cdn live demo" code has a bit error( codepen )

change this:
```
<script>
Vue.use(VueFinalModal);
```

for this:
```
<script>
Vue.use(VueFinalModal());
```

:blush:

**Comment by hunterliu1003** [comment]
Hi @jprando ,

Thanks for your feedback.

I fixed the cdn example in https://codepen.io/hunterliu1003/pen/ZEWoYeE
