### ISSUE TITLE
Scroll lock doesn't seem to work

### ISSUE THREAD

**Issue by erikas-tranauskas** [vue-final/vue-final-modal#42]
Hello, any idea why scroll lock doesn't work on my main page body tag? It doesn't seem to get the style="overflow: hidden" tag. I see no console errors or anything wrong, except this scroll bar.

**Comment by hunterliu1003** [comment]
Hi @erikas-tranauskas ,

If prop `lock-scroll` was set to `false`, scroll lock would be disabled. Please check that you don’t set lock-scroll to false.

If setting lock-scroll to true still not work, could you please provide a reproduction link with codepen or jsfiddle so that I can help you

**Comment by erikas-tranauskas** [comment]
Thank you for your answer.

I tried this lock-scroll prop and it seems that it is working - I can't scroll using my mouse while modal is open, the only problem is that the scroll bar itself is still visible. If I pass the lock-scroll false parameter, then I can scroll with my mouse and the bar itself is still visible. I guess it's something with my CSS or HTML.

In which part of code the CSS parameter is passed to the main body tag? Maybe I could debug it.

**Comment by hunterliu1003** [comment]
> In which part of code the CSS parameter is passed to the main body tag? Maybe I could debug it.

The lockScroll feature was controlled by methods `disableBodyScroll` and `enableBodyScroll` (code is here [bodyScrollLock.js](https://github.com/vue-final/vue-final-modal/blob/master/lib/utils/bodyScrollLock.js)), and bodyScrollLock is copied from [body-scroll-lock](https://www.npmjs.com/package/body-scroll-lock).

**Comment by erikas-tranauskas** [comment]
I just saw that my version is 0.19.1 only, maybe that's the case? I tried npm update vue-final-modal but I only got upgraded to 0.19.2.

**Comment by hunterliu1003** [comment]
You can try to update the version to v0.21.3. Checkout if the issue was still exist.

**Comment by hunterliu1003** [comment]
I refactor lock-scroll behavior in 0.21.x

**Comment by erikas-tranauskas** [comment]
npm update vue-final-modal only gives the 0.19.2 version. Could you update it to 0.21?

**Comment by hunterliu1003** [comment]
The vue-final-modal@0.21.3 was published in https://www.npmjs.com/package/vue-final-modal/v/0.21.3

**Comment by erikas-tranauskas** [comment]
Hm, yes, I see. I still get only 0.19.2. I will try to reinstall it.

**Comment by erikas-tranauskas** [comment]
Updated, ok now I see the bodyScrollLock.js but still the scrollbar is visible. :( I will try to debug the js.

**Comment by erikas-tranauskas** [comment]
Ohh, nice it is working now. I updated the version but didn't restarted the watch build function. After full rebuild everything is fine. Thank you!
