### ISSUE TITLE
Get Exposed props from the component using useModal

### ISSUE THREAD

**Issue by mdominiak2** [vue-final/vue-final-modal#420]
Is there any way to get exposed things from the component using useModal?

e.g. We have component `CatalogPopup` and this component expose one function `exposedFunction`.

```
const modal = useModal({
    component: CatalogPopup,
});
modal.open();
...
modal.component.exposed.exposedFunction();
```

Is it possible?

**Comment by hunterliu1003** [comment]
@mdominiak2 
Currently I don't think there is a way to get exposed props by using useModal. If possible you can give more context or background of your use case, I am willing to give you alternatives.
