### ISSUE TITLE
Scrollable modal on mobile with keyboard opened

### ISSUE THREAD

**Issue by CavalcanteLeo** [vue-final/vue-final-modal#43]
### Version

vue-final-modal: ^0.21.3"
nuxt: ^2.14.0

---

Long modals(scrollable) with input is buggy on iOS (maybe on android as well)
the CSS is not capable to resize the max-height of modal (tested on iOS only)
to reproduce the bug, open the link above on a mobile (iPhone)
[Link not available anymore]

**Here's explaining this bug:**

https://github.com/adamjgrant/a-viewport-that-works
https://medium.com/samsung-internet-dev/toolbars-keyboards-and-the-viewports-10abcc6c3769
https://meta.discourse.org/t/guessing-the-keyboard-height-on-ios/70919/19
https://stackoverflow.com/a/10925938/1971096

Btw, this is the best nuxt modal i found.
Keep doing this great job, and let's make it more mobile friendly

**Comment by hunterliu1003** [comment]
Hi @CavalcanteLeo ,

Thank you for spending time to find these information and provide the reproduction link.
I checkout the dialog component in Vuetify and BootstrapVue, they seam to have the same issue.
vue-final-modal as a renderless component, I want to keep the built-in CSS style as little as possible, and give all the flexibility of defining CSS style to developers. However, we can still try to use [a-viewport-that-works](https://github.com/adamjgrant/a-viewport-that-works) to improve [the current example VModal](https://vue-final-modal.org/examples/recommended-use#vmodalvue) in docs.
