### ISSUE TITLE
type error for default emits

### ISSUE THREAD

**Issue by minkoonim** [vue-final/vue-final-modal#447]
### Version

vue-final-modal: 4.5.4
vue: 3.4.33
nuxt: 3.12.4

### OS
Ubuntu

### Reproduction Link
not a runtime bug

### Steps to reproduce
open type definition to check "type UseModalOptions" from "Modal.d.ts"
![image](https://github.com/user-attachments/assets/17e387a6-4914-4629-9147-94dc3b6d324c)
![image](https://github.com/user-attachments/assets/ea63d169-7794-4cd3-abdd-a824ed2aa7c1)

### What is Expected? & What is happening?
UseModalOptions<ModalComp<T>>['attrs'] has correct type,
while useModalOptions lacks onClosed and so on.

**Comment by minkoonim** [comment]
oh man I realized it was my problem closed.

**Comment by beyto1974** [comment]
I have the same issue running version 4.5.5. So, the problem is not resolved.
