### ISSUE TITLE
Add event stream into $vfm.show

### ISSUE THREAD

**Issue by finnpham** [vue-final/vue-final-modal#53]
I have created 1 modal-confirm for global and used `$vfm.show('name-modal', params)`. But

 When i closed modal, i need have event emit => to listen comfirm or closed. 
With some ways i want it like: `$vfm.show().then()` or maybe with `event streaming in RXJS`  ( `$vfm.show().subscribe(change)`)

Thanks you so much for your contribute :smile:

**Comment by finnpham** [comment]
And one more: that render component modal. example: when not show modal => remove it from DOM ( help performance well than ). 
![image](https://user-images.githubusercontent.com/76545073/109757336-25cc3300-7c1c-11eb-8fd9-604247e29dde.png)

**Comment by hunterliu1003** [comment]
Hi @finnpham,

Thanks for your feedback.

1.
> With some ways i want it like: `$vfm.show().then()` or maybe with `event streaming in RXJS` ( `$vfm.show().subscribe(change)`)

I will give it a try on this weekend.  For now, you can use `@opened` event.

2.
> And one more: that render component modal. example: when not show modal => remove it from DOM ( help performance well than ).

You can set prop `:ssr="false"` to remove it from DOM.

**Comment by finnpham** [comment]
Thanks you so much @hunterliu1003 , you support quickly. :D 

I'm looking forward to No.1 :D if it can work, please ping me....
In issue No.2 => it work. but with mobile device it have error message like img.

![image](https://user-images.githubusercontent.com/76545073/109767420-1fdd4e80-7c2a-11eb-9e27-49d2f70dd073.png)

**Comment by hunterliu1003** [comment]
Thanks for reply the issue, I create a new issue for No.2 bug

**Comment by hunterliu1003** [comment]
Released an enhancement that API `$vfm` return `Promise` in version:
- v2.2 for Vue 2
- v3.2 for Vue 3
