### ISSUE TITLE
Problem with v-model which comes from another component as a prop

### ISSUE THREAD

**Issue by erikas-tranauskas** [vue-final/vue-final-modal#59]
### Version

vue-final-modal: 0.21.3
vue: 2.6.12

I encauntered a problem while trying to close the modal by clicking anywhere on the background. What is strange that if I use a button with @click event - it works fine.

Here is a tag of my vue modal which is in component called **testModal**:
`  <vue-modal v-bind="$attrs" :classes="containerClasses" :content-class="contentClasses" v-model="this.modalShow" @cancel="cancel">
`
Now modalShow variable comes from another component as a property:
`    @Prop({ default: () => {}}) modalShow!: boolean`

The modalShow prop is false in the beginning and I have a click event which sets it to true. This modalShow prop is binded to the testModal component like this:
`      <test-modal
          :modal="this.modalShow"
          :urls="this.urls"
          :translations="translations"
      />`

Now the cancel function on testModal component looks like this:
`    cancel() {
      console.log('test');
      this.modalShow = false;
      this.$emit('cancel');
    }`

And if I invoke it by some button inside the modal itself - it works perfectly and closes the modal. Now if I click on the outside of modal - I get the following error:

vue.esm.js:1897 TypeError: Cannot use 'in' operator to search for 'modal' in null
    at Proxy.set (vue.esm.js:1085)
    at callback (OfferHistoryModal.vue?44a5:149)
    at invokeWithErrorHandling (vue.esm.js:1863)
    at VueComponent.invoker (vue.esm.js:2188)
    at invokeWithErrorHandling (vue.esm.js:1863)
    at VueComponent.Vue.$emit (vue.esm.js:3897)
    at VueComponent.onClickContainer (VueFinalModal.esm.js:1)
    at click (VueFinalModal.esm.js:1)
    at invokeWithErrorHandling (vue.esm.js:1863)
    at HTMLDivElement.invoker (vue.esm.js:2188)

It doesn't even invoke the cancel function because there is no console.log output in the console.

Any ideas? I could provide more information if needed. Closing works fine if I create this showModal variable inside the modal component, but I need it to be on the parent component and be passed like a prop.

**Comment by hunterliu1003** [comment]
Hi @erikas-tranauskas,

Please checkout the Documentations https://vue-final-modal.org/examples/recommend.

Try modify your component like:

```
<test-modal v-model="modalShow" :urls="urls" :translations="translations" />
```

```
<vue-modal v-bind="$attrs"  :classes="containerClasses" :content-class="contentClasses" v-on="$listeners">
```

remove this `@Prop({ default: () => {}}) modalShow!: boolean`

**Comment by erikas-tranauskas** [comment]
Thank you for your answer. Problem was that I was trying to set v-model for Modal component as this.showModal, and it had to be just showModal. Sorry for your time.
