### ISSUE TITLE
How to use with VueJS 3

### ISSUE THREAD

**Issue by RomkaLTU** [vue-final/vue-final-modal#65]
I'm not new to Vue but completely lost on how to use it with VueJS 3. Documentation is incomplete at this point. 

I'm just getting errors like:

```
Invalid VNode type: undefined (undefined)
```

When toggling visibility getting: 

```
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of undefined
```

**Comment by hunterliu1003** [comment]
Hi @RomkaLTU,

Please provide a reproduction so that I can help you.

If you are using Vue 3, you need to check the version of vue-final-modal higher than 3.0.0

**Comment by MysteryGenius** [comment]
Hi 

The current Vue 3 documentation recommends using Vue.use(), which has been replaced with createApp(). Using it as a plugin 
`createApp(...).use(VueFinalModal())` Is there a new way to use the modal in Vue3

**Comment by PeterEsenwa** [comment]
> I'm not new to Vue but completely lost on how to use it with VueJS 3. Documentation is incomplete at this point.
> 
> I'm just getting errors like:
> 
> ```
> Invalid VNode type: undefined (undefined)
> ```
> 
> When toggling visibility getting:
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property 'parentNode' of undefined
> ```

I am having the same issue using vue-final-moda@3.1.0 and vue@3.0.7. I followed the HOC example to the letter and still encountered this.

**Comment by hunterliu1003** [comment]
Hi @PeterEsenwa,

Please provide a reproduction so that I can help you.

Which HOC example code will run into the error?

**Comment by mixalbl4-127** [comment]
docs completly does not work with v3.

1. `main.ts`
```typescript
import VueFinalModal from "vue-final-modal";
...
app.use(VueFinalModal);
```
![image](https://user-images.githubusercontent.com/3511307/114385936-47182b80-9b99-11eb-8a4c-d96cf40ac68f.png)
why?? `vue-final-modal` and `VueFinalModal` tags doesn't recognized.

2. Your example: `<vue-final-modal v-bind="$attrs" classes="modal-container" content-class="modal-content" v-on="$listeners">`
give this error:
`2:100  error    The $listeners is deprecated                  vue/no-deprecated-dollar-listeners-api`

3. `::v-deep` is deprecated too.

and this issues fount even before I make first basic example.
How to use it??? It doesn't work with v3

```
    "vue-final-modal": "^3.1.0",
    "vue": "^3.0.7",
```
@hunterliu1003

**Comment by mixalbl4-127** [comment]
Loool! Three hours of error searching!!!
ALL regular modules have to be used in `.use` without calling!
What is this kludge for?! For options? Options can be passed in second argument in `.use`

![image](https://user-images.githubusercontent.com/3511307/114388805-e0950c80-9b9c-11eb-9653-17105613d883.png)

**Comment by mixalbl4-127** [comment]
`Component emitted event "input" but it is neither declared in the emits option nor as an "onInput" prop.`
close and cancel doent work

+ any emits must be in `emits: []` array in v3...

**Comment by mixalbl4-127** [comment]
![image](https://user-images.githubusercontent.com/3511307/114399512-aaaa5500-9ba9-11eb-8726-5ae61e578518.png)

**Comment by soylomass** [comment]
I have the same problem with $listeners (deprecated), and not being able to emit input to close.

**Comment by hunterliu1003** [comment]
The v3 documentation is still work in progress, it's not complete enough. I will keep working on it.

Here is the basic `HOC` example in Vue 3:

```vue
<template>
  <vue-final-modal v-slot="{ close }" v-bind="$attrs">
    <div>Hello Vue Final Modal</div>
    <button @click="close">close modal</button>
  </vue-final-modal>
</template>

<script>
export default {
  name: 'VModal',
  inheritAttrs: false
}
</script>
```

Please checkout: https://v3.vue-final-modal.org/guide/scoped-slot#close

1. I will update the docs to avoid misunderstandings, maybe like:

    ```
    import createVfm from 'vue-final-modal'
    ...
    app.use(createVfm())
    ```

2. `$listeners` is deprecated, so just remove it.

    Now, you can use `v-slot="{ close }"` in HOC template trigger close modal in [vue-final-modal@3.2.1](https://www.npmjs.com/package/vue-final-modal/v/3.2.1)
    
3. ::v-deep is deprecated
  
    replace 
    
    ```css
    ::v-deep .modal-container { ... }
    ```
    
    to
    
    ```css
    ::v-deep(.modal-container) { ... }
    ```
