### ISSUE TITLE
Importing Vue Final Modal in component (Vue 3)

### ISSUE THREAD

**Issue by microHoffman** [vue-final/vue-final-modal#67]
### Version

vue-final-modal: 3.0.1
vue: 3.0.7

### OS

Windows

### Problem
Hello, first - thank you for your work. I haven't had any problem with vue-final-modal while I imported it globally via Vue.use(). However I am doing some refactoring now and it would make better sense, if I could import it just in my high-level component BaseModal.vue . Unfortunately, I couldn't make this work. Here is my code: 

```
<template>
  <vue-final-modal
    classes="modal-container"
    content-class="modal-content"
    v-model="show"
  >
  // etc....
  </vue-final-modal>
</template>

import VueFinalModal from "/node_modules/vue-final-modal";

export default {
  name: "BaseModal",
  components: { VueFinalModal },
  data() {
    return {
      show: false 
    }
  }
```

If I would try this code, it would compile ok, but when I trigger the show button, this error occurs: "[Vue warn]: Invalid VNode type: undefined". I tried to look up in your documentation but unfortunately I found nothing on this problem.

Don't you have any idea, if is it possible to import VueFinalModal only in component and not globally? Thank you for your time and help, take care.

**Comment by hunterliu1003** [comment]
Hi @microHoffman,

Thanks for your question.

Currently vue-final-modal only supports the use of global registration.

**Comment by microHoffman** [comment]
Hello @hunterliu1003,
thanks for your quick response:).
Have a nice evening.
