### ISSUE TITLE
Setting default class to all opened modals

### ISSUE THREAD

**Issue by erikas-tranauskas** [vue-final/vue-final-modal#79]
vue-final-modal: 0.21.3
vue: 2.6.12

Hello,

I am trying to put a class on every modal opened with vue-final-modal component. I am using the following example: https://vue-final-modal.org/examples/recommend
Is it possible to check if modal is currently opened in VModal.vue component?

Code:
```
<template>
  <vue-final-modal v-bind="$attrs" :classes="containerClasses" class="modal-open" :content-class="contentClass" v-on="$listeners">
    <div class="modal__header">
      <slot name="header"></slot>
    </div>
    <div class="modal__body">
      <slot></slot>
    </div>
    <div class="modal__footer">
      <slot name="footer"></slot>
    </div>
  </vue-final-modal>
</template>

```
I want to put the class modal-open only if modal is opened.

**Comment by erikas-tranauskas** [comment]
Currently I managed to achieve this by passing an extra property from my child modal component. But I would like to somehow catch the v-model variable and see modal status without any extra props.

**Comment by hunterliu1003** [comment]
@erikas-tranauskas 

As you said, the modal value can only be obtained by passing props to child components.

What do you think if we put the modal status into the scoped slot.

```
<vue-final-modal v-slot:default="someModalStatus">
</vue-final-modal>
```

**Comment by erikas-tranauskas** [comment]
Looks good I think.

Just to clarify a little, my current code VModal.vue:
`  <vue-final-modal v-bind="$attrs" :class="{ 'modal-open': show }" :classes="containerClasses" :content-class="contentClass" v-on="$listeners"></vue-final-modal>
`
And my parent component:
`    <v-modal v-model="show" :show="show" v-bind="$attrs" class="discount-modal" @cancel="cancel" @confirm="confirm"></modal>
`
I passed the `show` prop to see the status of modal on my VModal component. So if you put the modal status into v-slot, I could reach it on VModal.vue without my extra prop?

**Comment by hunterliu1003** [comment]
> I passed the `show` prop to see the status of modal on my VModal component. So if you put the modal status into v-slot, I could reach it on VModal.vue without my extra prop?

Yes.

If using scoped-slot, you can only write as follows:

```vue
<vue-final-modal v-bind="$attrs" v-on="$listeners">
  <template  v-slot="{ visible }">
    <div :class="{ 'modal-open': visible }"></div>
  </template>
</vue-final-modal>
```

This is still invalid:

```vue
<vue-final-modal v-bind="$attrs" :class="{ 'modal-open': visible }"  v-slot="{ visible }" v-on="$listeners">
</vue-final-modal>
```

**Comment by erikas-tranauskas** [comment]
This would be really cool, should I leave this topic open for now?

Thank you for your fast response btw.

**Comment by hunterliu1003** [comment]
Maybe you can try this for now

```vue
<template>
  <vue-final-modal v-bind="$attrs" v-on="$listeners" :class="{ 'modal-open': value }"> </vue-final-modal>
</template>

<script>
export default {
  inheritAttrs: false,
  props: {
    value: { type: Boolean, default: false }
  }
}
</script>

```

**Comment by hunterliu1003** [comment]
> This would be really cool, should I leave this topic open for now?
> 
> Thank you for your fast response btw.

yeah

I will work on an enhancement for providing modal status in scoped-slot.

Maybe released in 2 week later
