### ISSUE TITLE
get instance into setup for @nuxtjs/composition-api

### ISSUE THREAD

**Issue by mityaGitHub** [vue-final/vue-final-modal#80]
When I try to take the instance component I get an error

`import {defineComponent} from '@nuxtjs/composition-api'`
`setup(_, ctx) {`
`  const {$vfm} = ctx`
`}`
> ERROR in pages/contacts.vue:116:12
> TS2339: Property '$vfm' does not exist on type 'SetupContext'.
>     115 |   setup(_, ctx) {
>    116 |     const {$vfm} = ctx
>          |            ^^^^^^

or
`import {defineComponent} from '@nuxtjs/composition-api'`
`setup(_, ctx) {`
`  const {$vfm} = ctx.parent`
`}`
> ERROR in pages/contacts.vue:116:12
> TS2339: Property '$vfml' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>> | null'.
>     115 |   setup(_, ctx) {
>    116 |     const {$vfm} = ctx.parent
>  &nbsp;       |            ^^^^^^

or
`import {defineComponent} from '@nuxtjs/composition-api'`
`setup(_, ctx) {`
`  const {$vfm} = ctx.parent?.$nuxt`
`}`
> ERROR in pages/contacts.vue:116:12
> TS2339: Property '$vfml' does not exist on type 'NuxtApp | undefined'.
>     115 |   setup(_, ctx) {
>    116 |     const {$vfm} = ctx.parent?.$nuxt
>         |            ^^^^^^

If I return an instance from hook useContext I get an error at runtime

`import {defineComponent, useContext} from '@nuxtjs/composition-api'`
`setup() {`
`  const {$vfm} = useContext()`
`.....`
`  $vfm.show(.....)`
`}`
>TypeError: Cannot read property 'show' of undefined

how do i get instance inside the setup function ?

### Version

vue-final-modal: v2.1.0
nuxt: v2.15.4
@nuxtjs/composition-api: v0.22.4

### OS
Windows

**Comment by hunterliu1003** [comment]
@mityaGitHub,

I did not try to use vue-final-modal with composition-api.
I am not sure if this is possible.

**Comment by mityaGitHub** [comment]
To solve the problem, I wrote this hook:

`hooks/useModal.ts` 
```ts
import Vue from 'vue'
import { getCurrentInstance, computed, ComputedRef } from '@vue/composition-api'
import { VueFinalModalProperty } from 'vue-final-modal/lib';

export default function useModal() : VueFinalModalProperty {
  const vm = getCurrentInstance();
  if (!vm)
    throw new Error("This must be called within a setup function.");
  return  vm.proxy['$vfm'];
};
```
The call inside the setup function looks like this:
```ts
import useModal from '~/hooks/useModal'
....
setup(_, ctx) {
    const $modal = useModal()
...
    $modal.show({
        component: 'TModalCallsList',  .....
```
The errors are gone, the module works. WOW!

**Comment by Mini-ghost** [comment]
> `import {defineComponent} from '@nuxtjs/composition-api'`
> `setup(_, ctx) {`
> ` const {$vfm} = ctx.parent`
> `}`
> 
> > ERROR in pages/contacts.vue:116:12
> > TS2339: Property '$vfml' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>> | null'.
> > 115 |   setup(_, ctx) {
> > 116 |     const {$vfm} = ctx.parent
> >         |            ^^^^^^

@mityaGitHub 

This error is because `parent` maybe is `null`, you can try this code below.

```ts
// typescript
import { defineComponent } from '@nuxtjs/composition-api'

export default defineComponent({
  setup(_, ctx) {
    const { $vfm } = ctx.parent!
    
    // other code ...
  },
})
```

But using hook to solve is really great ! ! !  I love it. 🙌

**Comment by hunterliu1003** [comment]
Feel free to re-open this issue if your problem is not resolved
