### ISSUE TITLE
Documentation Tool?

### ISSUE THREAD

**Issue by mikeerickson** [vue-final/vue-final-modal#85]
I have a question about your docs. Did you use a template which is served with Nuxt (I see the powered by Nuxt at the bottom).

I have been considering moving my various oss projects to VitePress and figure that is what you were using?

**Comment by hunterliu1003** [comment]
I used [nuxt/content](https://content.nuxtjs.org/) with the official [docs theme](@nuxt/content-theme-docs).
You can easily use [create-nuxt-content-docs](https://github.com/nuxt/content/tree/dev/packages/create-nuxt-content-docs) to build your docs.

I am also trying to use `vitepress` to replace `nuxt/content` to write documents for a better development experience.
But vitepress is still early WIP, I'm not sure it is a good idea to replace all documents with vitepress now.

vitepress and @nuxt/content-theme-docs are both awesome

**Comment by mikeerickson** [comment]
@hunterliu1003 In addition to VitePress, I have reviewed VuePress which seems pretty slick as well (and more mature) but I would like to learn Nuxt so using nuxt/content would be a win win approach.

Thanks for response, much appreciated.
