### ISSUE TITLE
transition not working propery when using Array or Object type for "content-class"-prop 

### ISSUE THREAD

**Issue by Roxas92** [vue-final/vue-final-modal#92]
### Version

vue-final-modal: v3.1.0
vue: 3.0.0

### OS

Windows

### Reproduction Link
https://github.com/Roxas92/vfm-transition-issue

### Steps to reproduce
Clone the repo, install dependencies and run e.g. `npm run serve`.
- Click "Open Modal (WORKING example)"-Button to see a smooth entry transition for the modal
- Click "Open Modal (BROKEN example)"-Button to see that the entry transition is no longer working while the leave transition does

### What is Expected? / What is actually happening?
The second example is not acting like the first one. Even though the only difference between those two is that the second example uses an array for the `content-class`-prop while the first one is using a string.

I already experiences this issue a while ago and already mentioned this here https://github.com/vue-final/vue-final-modal/pull/62#issuecomment-805960767. But unfortunately I was not able to reproduce the case, so I went back and used `v1.8.7`, where - for some reason - it's working. Today I wanted to upgrade `vue-final-modal` to take advantage or your new dynamic modals feature and it was again broken. So I took some time to find whats causing the issue and I found out that once I use either an `Array` or an `Object`-type for `content-class` that the entry transition is no longer working.

While I was trying around I noticed that whenever I put some kind `Array` or `Object`-type for any of the properties that it begins to bug around. 

I will definitely try around to find a solution for myself as well, but would be great if you could check out this weird behaviour as well.

**Comment by hunterliu1003** [comment]
Hi @Roxas92,

Thank you for your contribution, you let me reproduce this issue very easily.

I also noticed that the issue only occur in version in Vue 3.

**Comment by Roxas92** [comment]
Awesome, great you found a fix for this! 💯

**Comment by hunterliu1003** [comment]
Bugfix was released in vue-final-modal@3.2.1
